### ISSUE TITLE
Error when start. OS X Mojave

### ISSUE THREAD

**Issue by Piohm** [sidneys/pb-for-desktop#101]
## 🤷🏽‍♂️ Current Behaviour

"Crash" (error needing app's restart) when app starts.
<img width="1225" alt="pberror" src="https://user-images.githubusercontent.com/34289121/54546088-51a86c80-49a3-11e9-99cd-5c84b594a655.png">
[pberror.txt](https://github.com/sidneys/pb-for-desktop/files/2979197/pberror.txt)

## 🎯 Expected Behaviour

 1. Start PB for desktop
 2. PB starts as usual and shows all regular menus (people-devices-etc.)
 3. Error window replaces the menu window "Aw, Snap! An error."

## 🏡 Environmental Context

**App Version**
v8.12.0
**Installation Type** 
Setup
**Operating System**
OS X Mojave 10.14.3 MBP Retina 15" late 2013

**Comment by sidneys** [comment]
@Piohm  

Thank you for your feedback. Was this issue resolved with one of the [recent releases](https://github.com/sidneys/pb-for-desktop/releases)?

Cheers,
S

**Comment by Piohm** [comment]
Thanks for your answer! It seems to be fixed indeed, v8.18.2. Sorry for my late answer. I'll mark this issue as fixed.
