### ISSUE TITLE
A JavaScript error occurred in the main process Uncaught Exception.

### ISSUE THREAD

**Issue by ohynek96** [sidneys/pb-for-desktop#102]
## 🤷🏽‍♂️ Current Behaviour

Every time I try to run this app I get this error:

![Capture](https://user-images.githubusercontent.com/27403884/55615955-08bd2a00-5791-11e9-8069-f1a22c84fde5.PNG)

I tried older version and the latest version that start normally is v8.8.8 .

## 🎯 Expected Behaviour

It should start.

## 👟 Steps to Reproduce (S2R)

Run the app.

## 🏡 Environmental Context

**App Version**
v8.15.0
**Installation Type** 
Setup
**Operating System**
Windows 10 Pro x64 (17134.677)

**Comment by sidneys** [comment]
@ohynek96 

Thank you for your feedback. Was this issue resolved with one of the [recent releases](https://github.com/sidneys/pb-for-desktop/releases)?

Cheers,
S

**Comment by ohynek96** [comment]
Yes, it was fixed with the release 8.18.2 :-)
