### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by whispy** [sidneys/pb-for-desktop#104]
## 🤷🏽‍♂️ Current Behaviour

When the application is set to auto-update, the update fails with the following error message:
> There was a problem updating the application.
>
> Code signature at URL file:///Users/{my username}/Library/Caches/de.sidneys.pb-for-desktop.ShipIt/update.jhFwtUz/PB%20for%20Desktop.app/ did not pass validation: code failed to satisfy specified code requirement(s)

## 🎯 Expected Behaviour

Application would update normally with no error messages

## 👟 Steps to Reproduce (S2R)

1. Run v8.18.2
2. Turn in automatic app updates
3. App will try updating and will fail

## 🏡 Environmental Context

**App Version**
v8.18.2
**Installation Type** 
Normal? Don't recall exactly how installed
**Operating System**
MacOS 10.13.4

**Comment by sidneys** [comment]
@whispy 

Thanks. Will be immediately investigated.

**Comment by whispy** [comment]
@sidneys any update on this? I'm happy to provide more info or troubleshooting.

**Comment by sidneys** [comment]
@whispy This had to do with an expired development certificate. The notarization certificate has been updated in the meantime, thus it might be required to install the app manually.
