### ISSUE TITLE
"PB for Desktop cannot be opened because of a problem."

### ISSUE THREAD

**Issue by idzakoea** [sidneys/pb-for-desktop#108]
## 🤷🏽‍♂️ Current Behaviour
<img width="602" alt="Screen Shot 2019-07-26 at 4 51 49 PM" src="https://user-images.githubusercontent.com/53355157/61988847-b8dacb00-afec-11e9-9e86-8c4203964a8e.png">

<img width="886" alt="Screen Shot 2019-07-26 at 9 41 38 PM" src="https://user-images.githubusercontent.com/53355157/61988942-34894780-afee-11e9-9cc9-e50ecd58d8d8.png">

Error note when I try to open the application. It used to open and work just fine, but recently I started getting a notice about the application having an update; upon trying to update, I would get a different error. I uninstalled, reinstalled (multiple times), and I continue getting this new issue where I can't even open the application anymore. I have updated my macOS to the newest version, and the issue still isn't resolved.

## 🎯 Expected Behaviour
Application should have opened like usual, as it has done in the past.

## 👟 Steps to Reproduce (S2R)
 1. Uninstall PB for Desktop.
 2. Reinstall PB for Desktop.
 3. Engage opening application, and receive error message before the PB screen opens.

## 🏡 Environmental Context
**App Version**
v9.0.9
**Installation Type** 
dmg
**Operating System**
macOS Mojave
Version 10.14.6

**Comment by sidneys** [comment]
@idzakoea This issue should be fixed in the new version (10.0.1).
