### ISSUE TITLE
Not receiving notifications on macOS

### ISSUE THREAD

**Issue by charles-001** [sidneys/pb-for-desktop#109]
## 🤷🏽‍♂️ Current Behaviour

I'm not receiving notifications on my desktop.

I see the "PB for Desktop" device, but everything that is sent from the desktop or sent to that device from my phone gets stucks in "Sending" status.

## 🎯 Expected Behaviour

Receive a desktop notification whenever my phone does

## 🏡 Environmental Context

**App Version**
9.5.0
**Installation Type** 
Setup
**Operating System**
macOS Mojave 10.14.6

**Comment by GodLesZ** [comment]
Duplicate of #100

**Comment by sidneys** [comment]
Duplicate of #100, indeed. Thanks, @GodLesZ. Closing.
