### ISSUE TITLE
icon color

### ISSUE THREAD

**Issue by towo** [sidneys/pb-for-desktop#11]
GNOME really goes for a monochrome icon aesthetic in the top bar, with colours only representing actionable items. Could there be a toggleable option for a monochrome icon?

**Comment by sidneys** [comment]
@towo thanks for the suggestion. as monochrome tray icons follow UX best practices on all three platforms now this will be in one of the next minor releases. has been for a while - the coloured ones are recent. cheers.

**Comment by sidneys** [comment]
@towo Included in v2.9.61.
