### ISSUE TITLE
Unable to open pb-for-desktop in Debian 10 i3wm

### ISSUE THREAD

**Issue by maxtimbo** [sidneys/pb-for-desktop#115]
## 🤷🏽‍♂️ Current Behaviour

Installed 10.4.3.deb, 10.3.0.deb, and attempted to use the 10.3.0.AppImage all gave the same output in terminal:

`maxtim@WinBeast:~/Downloads$ pb-for-desktop 
[21568:1217/175931.296401:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/PB for Desktop/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
`

## 🎯 Expected Behaviour

It should open

## 👟 Steps to Reproduce (S2R)

download .deb, install using apt: `cd ~Downloads` `sudo apt install ./pb-for-desktop-10.4.3-amd64.deb`

## 🏡 Environmental Context

**App Version**
v10.4.3
**Installation Type** 
apt install
**Operating System**
Debian 10 Buster (Stable Branch)
i3wm (installed over mate)
polybar

**Comment by maxtimbo** [comment]
**Note:

I have tried `chown root:root` and `chmod 4755` as the error describes. I then get:
`tfinley@WinBeast:~/Downloads$ pb-for-desktop 
Trace/breakpoint trap
`

**Comment by sidneys** [comment]
@maxtimbo 

Thanks for the heads-up. Does this issue still occur in the [v10.5.0 release](https://github.com/sidneys/pb-for-desktop/releases)? 

Kind regards, S

**Comment by maxtimbo** [comment]
v10.5.0 deb was returning a mystic:
`Trace/breakpoint trap`
I grabbed the appimage. When trying to open via terminal:
`[32666:0125/010308.577953:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_pb-forn0Spuh/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap`

So same as before. I;m not going to bother trying to chmod chrome sandbox. Fairly confident my setup isn't the issue.

**Comment by felixcode** [comment]
a workaround from https://github.com/electron/electron/issues/17972
`sysctl kernel.unprivileged_userns_clone=1 `

> Enable the sysctl setting kernel.unprivileged_userns_clone to allow normal users to run unprivileged containers. This can be done for the current session with sysctl kernel.unprivileged_userns_clone=1 and can be made permanent with sysctl.d(5).
