### ISSUE TITLE
Cannot open main window

### ISSUE THREAD

**Issue by a-katsarov** [sidneys/pb-for-desktop#116]
## 🤷🏽‍♂️ Current Behaviour
Bug Report: When I click "Show PB for Desktop" I get the following error:

![screenshot-2019-12-20_22-51-50](https://user-images.githubusercontent.com/5220017/71291706-0aa93680-237c-11ea-913a-f281bb86c243.png)

## 🎯 Expected Behaviour
The expected is to open the window without errors.

## 👟 Steps to Reproduce (S2R)

Click the first item from the menu.

## 🏡 Environmental Context
**App Version**
v10.4.5
**Installation Type** 
deb
**Operating System**
Debian 10

**Comment by tahoe-vegas** [comment]
I am experiencing this issue as well on Ubuntu

**Comment by flodi** [comment]
Me too, on Mac.

**Comment by baali-boudjemaa** [comment]
i am using your app on fedora and when I click "Show PB for Desktop" I get the following error:
![Screenshot_20200120_181016](https://user-images.githubusercontent.com/12560413/72745698-55d28700-3b7e-11ea-8b57-bb951ca611b2.png)

**Comment by sidneys** [comment]
@a-katsarov @renoplane @flodi @baali-boudjemaa 

Thank you all for your info. This bug, as well as many others, have been addressed in the [v10.5.0 release](https://github.com/sidneys/pb-for-desktop/releases).

Please review the new version and update this issue accordingly.

Kind regards, S

**Comment by MockingMagician** [comment]
Hi @sidneys, forwarding that same error occurs on https://github.com/sidneys/pb-for-desktop/releases/tag/v10.5.0

**Comment by tahoe-vegas** [comment]
Yes, the update did not fix it for me

**Comment by MockingMagician** [comment]
Can be fixed with this PR https://github.com/sidneys/pb-for-desktop/pull/118

**Comment by turbovan** [comment]
I am getting the same error on Arch Linux install

**Comment by Merrit** [comment]
Same issue still on Manjaro with v10.5.0

**Comment by MockingMagician** [comment]
@turbovan @Merrit 

See PR #118 

Until it is not merged, clone, compile and install from that PR

See https://github.com/sidneys/pb-for-desktop/issues/117#issuecomment-583619930

**Comment by BackSeat** [comment]
Any plans for a release to address this issue?

Thanks

**Comment by sidneys** [comment]
@a-katsarov 
@MockingMagician

Thank you for the report and the related pull request by @MockingMagician.

This issue should be resolved as per the [new release](https://github.com/sidneys/pb-for-desktop/releases), which was just published. It seems to be identical to https://github.com/sidneys/pb-for-desktop/issues/117.

Please review the changes and file a new issue accordingly if the problem should reoccur.

Kind regards,
S
