### ISSUE TITLE
Any mouse dragging moves the window

### ISSUE THREAD

**Issue by tetious** [sidneys/pb-for-desktop#13]
The entire window seems to capture mouse drags, which is kind of annoying. It makes it difficult to select text for copy/paste or to use the mouse to highlight text to replace when typing.

Maybe this could be changed so only drags in the titlebar move the window like most apps?

**Comment by sidneys** [comment]
Thanks for the heads up. We'll test this as soon as possible.

**Comment by sidneys** [comment]
@tetious Fixed in 0a47efdbd5cae7c9a260b1c6c5b09bc1c082c521. Please review.

**Comment by tetious** [comment]
Looks great. Thanks!
