### ISSUE TITLE
Ghost notifications still in v3.1.0

### ISSUE THREAD

**Issue by ghost** [sidneys/pb-for-desktop#14]
Hello,

I have just installed the latest version 3.1.0 on macOS Sierra, and unfortunately the 'ghost' notifications are still there whenever I push a link to a contact. This happens either through the app itself, or even when I send things through the browser (I'm using Opera Stable).

Many thanks!

**Comment by sidneys** [comment]
Thanks for reporting. We'll look into this edge case asap.

**Comment by sidneys** [comment]
@ShintoPlasm 
Should be fixed in 0a47efdbd5cae7c9a260b1c6c5b09bc1c082c521, please review.

**Comment by ghost** [comment]
Looks like it's fixed now. Thank you!
