### ISSUE TITLE
Provide .tar.gz linux releases

### ISSUE THREAD

**Issue by bilelmoussaoui** [sidneys/pb-for-desktop#15]
I would like to make an Archlinux package for this application! Can you create a tar.gz package? or .zip ? you can do it easily using electron-builder; but not sure what are you using right now :)
Thanks!

**Comment by sidneys** [comment]
@bil-elmoussaoui Thanks for the input! The build system indeed uses electron-builder behind the scenes. Does Arch require pacman or tar.gz?

**Comment by bilelmoussaoui** [comment]
just provide .tar.gz would be more than enough

**Comment by sidneys** [comment]
@bil-elmoussaoui I'd prefer pacman, as using tar.gz build would require adding the platform type to all packages (because it's a platform-agnostic format). Just added a .pacman build to 0a47efdbd5cae7c9a260b1c6c5b09bc1c082c521 - can you conduct a test installation?

**Comment by bilelmoussaoui** [comment]
Well i couldn't install it. Normally the pacman build can be installed using `sudo pacman -U myfile.pacman`
Doing so shows this here 
```bash
warning: cannot resolve "gconf-service", a dependency of "pb-for-desktop"
warning: cannot resolve "gconf2", a dependency of "pb-for-desktop"
warning: cannot resolve "libappindicator1", a dependency of "pb-for-desktop"
warning: cannot resolve "libnotify4", a dependency of "pb-for-desktop"
warning: cannot resolve "libnss3", a dependency of "pb-for-desktop"
warning: cannot resolve "libxtst6", a dependency of "pb-for-desktop"
```
The package names are different from Ubuntu which causes this issue

**Comment by sidneys** [comment]
That was fast :-) Please try installing again now, those package dependency constraints were just removed for pacman.

**Comment by bilelmoussaoui** [comment]
It works just fine ;) I will create an AUR package so i can include all the dependencies within it ;) 
Anyway, i've noticed that the notifications sent from your application does not use any icon (but uses the information dialog by default) which is quite disturbing as i didn't knew that it was sent from PB at all :(

**Comment by bilelmoussaoui** [comment]
Here you go ! the package is done https://aur.archlinux.org/packages/pb-for-desktop/
Users can install it using `yaourt -S pb-for-desktop`
Btw, i've checked the desktop file and you seem to point to `/opt/Pb for Desktop/pb-for-desktop` I think the best way to do this, is to create a symlink from the /opt/Pb for Desktop/pb-for-desktop to /usr/bin/ and then use just `pb-for-desktop` In the Exec(in the desktop file)

**Comment by sidneys** [comment]
@bil-elmoussaoui Thank you for your contribution, that's awesome. We'll test the symlinking soon-ish, need an Arch VM setup for that. Cheers.
