### ISSUE TITLE
No notification on arch linux

### ISSUE THREAD

**Issue by gpreet1992** [sidneys/pb-for-desktop#16]
I have installed pb-for-desktop on my arch linux (manjaro edition Linux ******* 4.4.41-1-MANJARO #1 SMP PREEMPT Mon Jan 9 09:33:22 UTC 2017 x86_64 GNU/Linux, Desktop: Gnome 3.22.2 )

It all seems great and stable except one major issue. I am unable to receive notification at all. I tried sending a test mirror notification from my device multiple times but have not received a single lib-notify event from your app.

**Comment by sidneys** [comment]
@gpreet1992 Thanks for the report. Can you please re-test the issue with the additional ``pacman`` and/or ``AppImage`` package formats in 2e0a2b2ae433371c32fd565b12cda517048c2c6b ?

**Comment by andresilva** [comment]
It's also not working for me on macOS Sierra.

**Comment by sidneys** [comment]
@andrebeat Thanks for the report - can you please be a bit more specific? What should have been the result, and what happened? Does ist only apply to mirrored notifications, the clipboard, or subscriptions (like ifttt)?

**Comment by andresilva** [comment]
@sidneys Sorry for providing no information. I only use SMS notifications and mirrored notifications and I don't seem to receive any of those. For example, if I send the pushbullet test notification (in the mobile app) it isn't shown. Sending SMS is working and the SMS view is properly updated. 

*Edit: I can also provide any log data that you may need.*

**Comment by sidneys** [comment]
@andrebeat No problem - but could not reproduce the mirroring error yet.
Can you provide your specs (OS, platform etc.) and application version used?

Also, please review whether the most recent release may alleviate the issues encountered: 7530b2793b6ffeb3d9e6516841f7f64918bffac4

**Comment by andresilva** [comment]
I was using version 3.3.1 but I also tested previous versions and had the same problem. I now tested the latest version (3.4.0) and the problem still exists. I'm using macOS Sierra 10.12.3. I also have a Pushbullet pro subscription (I'm not sure that's relevant). My mobile phone is running Android 7.0 with the latest version of Pushbullet (although I have no problem receiving notifications when using the Firefox extension for example).

Another thing I noticed is that I get notifications for "direct pushes", i.e. when I receive a message directly through Pushbullet. And they're always replayed whenever I start PB-for-desktop. So it seems that only notification mirroring and SMS notifications are not working.

**Comment by sidneys** [comment]
@andrebeat 
The issues filed were just tested with an Nougat 7.1 emulated device, and both features worked well, including incoming and outgoing SMS. 

However, it required logging out and into the Android app once, using current Pushbullet credentials, and then activating the ``SMS Sync`` and ``Mirroring`` options inside the app and granting the app the required permissions when asked (thus completing the configuration).

Did you try this this approach? Also, why not join the [Dev Chat](http://gitter.im/sidneys/pb-for-desktop)?

**Comment by andresilva** [comment]
My issue was related to end-to-end encryption. @gpreet1992 Are you using end-to-end encryption? If that's the case try disabling it to see if it solves your problem.

**Comment by sidneys** [comment]
@andrebeat  @gpreet1992 E2E support is arriving in 7c941bc3849b3e0ce3099f8396cfd2eab515d7df 🍻
