### ISSUE TITLE
Exception on run

### ISSUE THREAD

**Issue by mshish** [sidneys/pb-for-desktop#17]
I'm using node v7.4.0 on Windows 10 x64. I've tried the installer and running from source with `npm run start`. I get the same exception with both (screenshot below) related to `icon-tray-default.png`.
![image](https://cloud.githubusercontent.com/assets/1867892/22342834/c335f9dc-e3c3-11e6-81d3-b5201c70a8f4.png)

**Comment by hotice** [comment]
Same in Ubuntu 16.10 64bit with pb-for-desktop 3.5.0:

![pb-for-desktop-bug](https://cloud.githubusercontent.com/assets/325449/22364695/e6a62ae6-e47b-11e6-8c9c-36e89a37fbd9.png)

**Comment by sidneys** [comment]
@mshish @hotice Thanks for the heads-up. The issue should be solved in b1757a4807504fef8f51dbae94a9febb5d7c18c3 and has been tested on Windows 10 (15014) and Ubuntu 16.04). Please re-test and comment.

**Comment by mshish** [comment]
Looks like that fixed it, thank you!
