### ISSUE TITLE
Add macOS Share Extension.

### ISSUE THREAD

**Issue by Rediwed** [sidneys/pb-for-desktop#18]
Hi!

I was hoping you would add a macOS Share Extension so webpages and such could be directly shared to a phone (similar to chrome-to-phone, but from safari to chrome mobile), like shown in the mockup I made below:
http://i.imgur.com/9YkwM5K.png

**Comment by sidneys** [comment]
@Rediwed 
Thanks for the suggestion! This feature would require separate platform-specific sub-projects (as Electron does not support app extensions yet), and code signing of the application as far as i know. We will investigate whether this can be achieved.
