### ISSUE TITLE
"Connecting" forever

### ISSUE THREAD

**Issue by bigggprogrammerboy** [sidneys/pb-for-desktop#19]
Running on 64-bit Mint 18, the install appears to be successful, but upon launch the green connecting animation appears but runs infinitely.

**Comment by ermsdev** [comment]
same issue on macOS Sierra 10.12.3

**Comment by sidneys** [comment]
@rbrandonc @sermshar 
Thanks for the report! Please investigate whether this issue still occurs with [v3.8.0](https://github.com/sidneys/pb-for-desktop/commit/023eb3458194f78dbae6a3a1d0dcd3a0a5dcf611). Cheers.

**Comment by ermsdev** [comment]
Fixed on MacOS, thanks!

**Comment by bigggprogrammerboy** [comment]
Fixed on mint!
