### ISSUE TITLE
Can't install latest version on linuxmint

### ISSUE THREAD

**Issue by wilfriedroset** [sidneys/pb-for-desktop#2]
Using the latest release 1.1.5 on a x64 linux mint 17.3, I can't install the package

<pre>
$ wget https://github.com/sidneys/pushbullet-desktop/releases/download/v1.1.5/pushbullet_for_desktop-linux-x64-v1.1.5.zip
--8<--
2016-07-07 20:21:46 (1.71 MB/s) - ‘pushbullet_for_desktop-linux-x64-v1.1.5.zip’ saved [30529825/30529825]
$ unzip pushbullet_for_desktop-linux-x64-v1.1.5.zip
Archive:  pushbullet_for_desktop-linux-x64-v1.1.5.zip
  inflating: pushbullet_for_desktop-linux-x64-v1.1.5/pushbullet-desktop_1.1.5_.deb  
$ sudo dpkg -i pushbullet_for_desktop-linux-x64-v1.1.5/pushbullet-desktop_1.1.5_.deb
dpkg: warning: parsing file '/var/lib/dpkg/available' near line 11535 package 'pushbullet-desktop':
 missing architecture
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 14 package 'pushbullet-desktop':
 missing architecture
dpkg: error processing archive pushbullet_for_desktop-linux-x64-v1.1.5/pushbullet-desktop_1.1.5_.deb (--install):
 package architecture () does not match system (amd64)
Errors were encountered while processing:
 pushbullet_for_desktop-linux-x64-v1.1.5/pushbullet-desktop_1.1.5_.deb
$ cat /etc/*release*
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
</pre>

Edit:

Seems like you've missed to define the arch in your [control file](https://www.debian.org/doc/manuals/debian-faq/ch-pkg_basics.en.html):

<pre>
less pushbullet-desktop_1.1.5_.deb:
pushbullet-desktop_1.1.5_.deb:
 new debian package, version 2.0.
 size 30520488 bytes: control archive=519 bytes.
     750 bytes,    13 lines      control              
 Package: pushbullet-desktop
 Version: 1.1.5-1
 Section: utils
 Priority: optional
 Depends: git, gconf2, gconf-service, gvfs-bin, libc6, libcap2, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libnss3, libxtst6, python, xdg-utils
 Recommends: lsb-release
 Suggests: gir1.2-gnomekeyring-1.0, libgnome-keyring0
 Installed-Size: 110912
 Maintainer: sidneys
 Homepage: http://sidneys.github.io/pushbullet-desktop
 Description: A lightweight cross-platform Pushbullet Client for OS X, Windows and Linux. It enables you to receive native system notifications in an unobstrusive way.
  A lightweight cross-platform Pushbullet Client for OS X, Windows and Linux. It 
  enables you to receive native system notifications in an unobstrusive way.
</pre>

The name of the resulting package should be like pushbullet-desktop_1.1.5_**amd64**.deb

**Comment by sidneys** [comment]
Hi @wilfriedroset, the pre-release builds were just updated. Please re-check if your problem got solved.

**Comment by wilfriedroset** [comment]
Just installed 2.9.2, works as expected. Thanks
Sorry for the late reply
