### ISSUE TITLE
Please change tray icons in Ubuntu

### ISSUE THREAD

**Issue by erezhdd** [sidneys/pb-for-desktop#20]
The default tray icon (gray-white shape) in Ubuntu is dim and fuzzy. Can you please make the default tray icon look like the nice app icon (green/white)? and also modify the paused icon accordingly?

**Comment by sidneys** [comment]
@erezhdd 
Thanks for the heads-up. Icon assets were updated in [v3.9.6](https://github.com/sidneys/pb-for-desktop/releases), please review.

**Comment by erezhdd** [comment]
I just installed v3.9.6. Works great as usual, but the tray icon is still the weird gray shape. Is there a way to switch tray icons from the UI/settings? I didn't find any.

**Comment by sidneys** [comment]
@erezhdd Can you provide a screenshot?

**Comment by sidneys** [comment]
@erezhdd 
Thanks again for testing, please try again with the latest version.

**Comment by sidneys** [comment]
Fixed in v3.9.8

**Comment by erezhdd** [comment]
Indeed. Thank you!

**Comment by SolarLiner** [comment]
The reasoning behind me making the new monochrome icons is that they fit well with the modern desktop environment (GNOME in my case) with them modulating color to match the theme. Another set of white icons, or even being able to choose from different icons is definitely possible, but needs tweaks in the code.
