### ISSUE TITLE
PB-for-desktop won't connect in Fedora 25

### ISSUE THREAD

**Issue by didli** [sidneys/pb-for-desktop#22]
## 🤷🏽‍♂️ Current Behaviour
After installing pb-for-desktop with the rpm package, running pb-for-desktop will show the PB desktop window and the tray icon, and try to connect without success (the window shows "Pushbullet connecting" and stay there).
I can see this in the log file :
`[08:12:14 2017-03-16] [BROWSER] [main.html] [reachable] false`   
My first thoughts was that my firewalld config was interfering, but the problem persists even after stopping it. 

## 🏡 Environmental Context
**App Version**
v3.9.99
**Installation Type** 
RPM
**Operating System**
Fedora 25 x64

Note : I was waiting for an app like this that could work in any distrib, so a big **thank you** for this ! Keep up the good work !

**Comment by sidneys** [comment]
@didli 
Thanks for the accurate report. Please retry with the new [v4.0.2](../releases) and report your findings.

**Comment by didli** [comment]
Works perfectly fine now. The window showed up and asked for my credentials as expected. There's not even a warning in the log file ^^ 
That was fast. Thank you for your work !

**Comment by sidneys** [comment]
@didli 
Thanks for the status. Closing.
