### ISSUE TITLE
[Ubuntu 16.10] System slowdown due to increased memory usage upon resume

### ISSUE THREAD

**Issue by SolarLiner** [sidneys/pb-for-desktop#23]
![screenshot from 2017-03-14 22-33-19](https://cloud.githubusercontent.com/assets/4302963/23992973/22b9fd1c-0a3f-11e7-9866-1e50332e3ae1.png)

## 🤷🏽‍♂️ Current Behaviour
When resuming from suspend (not checked after hibernation), one of two ```pb-for-desktop``` processes increases its memory usage until fully taking up all available RAM.
## 🎯 Expected Behaviour
Not to leak memory this much (duh? 😄)

## 👟 Steps to Reproduce (S2R)
1. Suspend machine
2. Resume machine
3. Wait and see as PB for Desktop eats your RAM away!
**App Version**
v3.8.0
**Installation Type** 
deb file install
**Operating System**
Ubuntu GNOME (16.10) 64-bit

![screenshot from 2017-03-16 11-27-20](https://cloud.githubusercontent.com/assets/4302963/23992932/0d9d9c9a-0a3f-11e7-9bb9-988ff1782299.png)

**Comment by sidneys** [comment]
@SolarLiner 
Thanks for the screenshots and report. Please retry with the new [v4.0.2](../releases) and report your findings.

**Comment by SolarLiner** [comment]
Installed latest version and will test around in the evening.

**Comment by SolarLiner** [comment]
... And again, I'm a victim of my own lazyness, not checking for app updates.

So far, memory is stable under v4.0.2!

**Comment by SolarLiner** [comment]
Reopnening as with v4.0.8 the problem surfaced again:
![screenshot from 2017-03-22 17-44-03](https://cloud.githubusercontent.com/assets/4302963/24209753/7792e37a-0f27-11e7-8164-282b917ac8d1.png)

Steps are the same, it just takes a little bit longer for PB for Desktop to eat all of the memory.

**Comment by SolarLiner** [comment]
Version 4.7.5 still shows this behavior.

**Comment by sidneys** [comment]
@SolarLiner 

Seems like a regression to me. Can you please test this again with the latest release? Thanks.
--> [Link](../releases)

**Comment by SolarLiner** [comment]
I couldn't test with 4.8.1 because of #39 but 4.8.9 still shows the behavior.

**Comment by sidneys** [comment]
@SolarLiner 
#39 has been resolved, please retest with v5.1. or later.

**Comment by SolarLiner** [comment]
So far so good, after a few days, and a lot of suspend/resumes (using that laptop for class notes). I'll give one more week to fully test before closing it.

**Comment by SolarLiner** [comment]
Was about to close it when he did it again...

What is it that you're trying to do? I'm thinking it's deeper than just PB for Desktop, although other system tray electron apps (such as Messenger for Desktop) don't show this behavior.

I've already updated to the latest version, 5.4.4.
![screenshot from 2017-04-11 08-32-06](https://cloud.githubusercontent.com/assets/4302963/24895678/f1280ea8-1e91-11e7-8f45-bc3c3bf5f14c.png)
![screenshot from 2017-04-11 08-32-17](https://cloud.githubusercontent.com/assets/4302963/24895679/f13d3af8-1e91-11e7-88fe-4d2052c56a51.png)

**Comment by sidneys** [comment]
@SolarLiner Any updates on this?

**Comment by SolarLiner** [comment]
I'm testing regularly, updating as the updates go... It does seem to be random though, as not all resumes yield memory leaks.

**Comment by SolarLiner** [comment]
Well after a month and no leaks, I'm closing this issue. Let's hope there's nothing superstitious about me closing this issue... 😂

**Comment by SolarLiner** [comment]
... And I'll have to reopen this again.

And for the occasion, I've turned my Desktop PC into a clean Ubuntu GNOME install. 

And the memory leak happened. Fast. And no sleep required. 

So I can attest that the problem doesn't come from my laptop. But I'm still asking, are another Ubuntu (or even any Linux distros) users facing the problem? I genuinely ask because it looks as if I was the only one.

(Now traditional) screenshot on my desktop PC: 

![screenshot from 2017-06-03 00-56-29](https://cloud.githubusercontent.com/assets/4302963/26747810/b49841ca-47f8-11e7-828f-e10fca6f7d2d.png)

**Comment by mfreeman72** [comment]
Yes, I can also report this happening on my laptop. Linux Mint 18.2 64-bit Cinnamon.

**Comment by SolarLiner** [comment]
So after a while of random memory leaks, I might have found that I was mislead before - **memory leaks also randomly happen on network status change**. And since I use my laptop and suspend it before moving, there might be a time where the computer loses network while it reacquires wi-fi signal. This is what I think actually trips `pb-for-desktop` and make it start building up memory onto infinity.

This might also be why the leak happened with my computer - as the WiFi dongle I use doesn't have an Ubuntu driver, I'm stuck sharing internet with my phone through USB. Unplugging it causes a network change - and the rest is history.

Further evidence towards this  is the fact that I have carefully avoided any ad-hoc network change on my desktop PC and I did not see any leaks in a while now.

But, it remains relatively random which makes me think there is even more to it than that...
