### ISSUE TITLE
No SMS notifications on Fedora Linux 25

### ISSUE THREAD

**Issue by aia832003** [sidneys/pb-for-desktop#24]
I am not seeing any notifications come through for SMS on Linux. System is running and other push notifications are coming through, but I don't get sound or popup for SMS.

PB for Desktop version 3.9
Fedora 25x64 with Gnome 3.22.2
Installed package via appimage build.

![pb bug](https://cloud.githubusercontent.com/assets/11007827/24039819/8e416bb6-0ad4-11e7-8bfc-a9dd17838a65.png)

**Comment by sidneys** [comment]
@aia832003  
Thanks for the screenshot. Please retry with the new [v4.0.2](../releases) and report your findings.

**Comment by aia832003** [comment]
@sidneys just installed update on both of my machines and still no SMS. Other pushes still successful. Keep up the great work on the app and let me know if I can help you can walk me through.

**Comment by andresilva** [comment]
I have the same problem on macOS. It works for all other push notifications but no sound or notification for SMS (although they do show up in the app).

**Comment by apippin** [comment]
I'm seeing the same issue on RHEL6 and Windows10 desktop clients.

**Comment by sidneys** [comment]
@aia832003 @aia832003 @apippin 

Please test this issue again with the latest version. All sms mirrong tests were conducted successfully so far, however using specific configurations (Android 7.1.1, macOS)
--> [Link](../releases)

**Comment by aia832003** [comment]
Thanks for all the work Sidney! I am now getting the following error...do you think I need to do a complete uninstall and delete user files?


![screenshot from 2017-04-01 14-08-03](https://cloud.githubusercontent.com/assets/11007827/24581634/dbad80bc-16e4-11e7-830c-2a86322c5e20.png)

**Comment by aia832003** [comment]
Should mention that this is with the update from today and now sms doesn't seem to reflect any changes or notifications.

**Comment by sidneys** [comment]
@aia832003 
Thanks for the report. The latter issue is known and tracked here: #39

**Comment by sidneys** [comment]
@aia832003 
Please re-test with the [latest version](../releases) and share your results.

**Comment by aia832003** [comment]
Awesome news! It works. No error prompt and SMS notifications are fixed.

**Comment by aia832003** [comment]
Thank you sidney!

**Comment by andresilva** [comment]
The latest version also fixes it for me (macOS).

**Comment by sidneys** [comment]
@aia832003 @andrebeat 

This is a team effort, thanks for your tidy & timely feedback as well 👍 . Closing.
