### ISSUE TITLE
High energy consumption on macOS

### ISSUE THREAD

**Issue by electronic-dk** [sidneys/pb-for-desktop#25]
## 🤷🏽‍♂️ Current Behaviour
The app starts with very low energy impact (even with arriving pushes):

<img width="407" alt="screen shot 2017-03-17 at 16 44 22" src="https://cloud.githubusercontent.com/assets/2945527/24069379/d6d75370-0bb7-11e7-9fbc-331867328108.png">

But at some point (sorry, I couldn't identify the event which leads to that, looks like it just starts happening) the PB for Desktop Helper process starts hogging the battery:

<img width="456" alt="screen shot 2017-03-17 at 18 04 07" src="https://cloud.githubusercontent.com/assets/2945527/24069387/2d93f1c8-0bb8-11e7-82db-fd6e55be7c41.png">

And after a couple of hours, it gets into the top three energy consuming apps (with the first two being Chrome and Intellij Idea running in the foreground):

<img width="445" alt="screen shot 2017-03-17 at 22 06 17" src="https://cloud.githubusercontent.com/assets/2945527/24069416/dd832e28-0bb8-11e7-8461-18a847c3289a.png">

The only thing which appears to be helping to mitigate this is to reinstall the app.

## 🎯 Expected Behaviour
The background process keeps the energy consumption at the same low level as when it starts.

## 👟 Steps to Reproduce (S2R)
 1. Install the app and log in
 2. Wait
 3. ????
 3. ~~PROFIT~~ BUG

## 🏡 Environmental Context
**App Version**
v4.0.6
**Installation Type** 
Disk image
**Operating System**
masOS Sierra 10.12.3

**Comment by sidneys** [comment]
@electronic-dk 
Thanks for your report and constructive commentary at Gitter as well.
Version [4.1.0](../releases/) was just released, addressing said performance issues.
Please review and share your findings with us.

Cheers.

**Comment by electronic-dk** [comment]
@sidneys I've cleared the app's cache, removed all of the data, installed the new version and so far so good. Energy consumption is around 0.0 - 0.1 in the background, and the main process goes up to 1.0 for a second or two every once in a while or when a push arrives, then it goes back to 0.0 - 0.1. I'll keep monitoring

Thanks for the version :) 👍

**Comment by electronic-dk** [comment]
@sidneys I have another finding: the app doesn't like reconnecting: the energy consumption spikes and remains high after reconnecting, the only thing that helps is logging out and back in.

**Comment by sidneys** [comment]
@electronic-dk 
Thanks for the update. The energy spikes after reconnecting are most likely related to other components than the ones addressed in 4.1.0, please create a new issue for this problem [here](../issues/new). Cheers.

**Comment by bjptwist** [comment]
Hi. I'm using version 5.9.6 and I'm having the exact same issue with high cpu consumption. Basically, if I quit the app and start it again the average cpu usage is around 2,0, being one of the top battery consuming apps. As soon as I open the main window (clicking in "Show PB for Desktop") and close it, the cpu usage drops right away.
