### ISSUE TITLE
Automatic reconnection for PB4D

### ISSUE THREAD

**Issue by erezhdd** [sidneys/pb-for-desktop#27]
PB4D (4.1.0 / Ubuntu 16.04) is already quite usable and mature. Specifically, is has a nice "Reconnect.." button to allow it to reconnect to the PB service following a network disconnection or a machine suspend/resume. There is also automatic reconnection, but it sometimes misses on detection.

This issue is about requesting a more advanced automatic reconnection. It should be [a] stable, disregarding potential network configuration issues or bugs in the external OS facilities, and [b] cross-platform - since PB4D targets also Windows and Mac.

The idea is to base PB service detection on a periodical ping / heartbeat message that is sent from the client directly to the PB service (e.g,, using actual ping (ICMP), or a fresh HTTP connection). Failure to receive reply (or several replies, when connection quality is bad) should be considered as connection down event. Success (again, one or several) should be considered as connection up event. Following these events, PB4D client should either disconnect or reconnect automatically.

This issue is a follow-up to issue #21 and proposed together with issue #26 .

**Comment by sidneys** [comment]
@erezhdd 
This feature just landed in version [v5.0.0](../releases).
Please review and share your findings.

**Comment by erezhdd** [comment]
Installed. Basic regression tests - startup, connection - PASS.
And, more important - thank you for doing this. 
Will report further later.

**Comment by sidneys** [comment]
@erezhdd Great. Thanks.

**Comment by sidneys** [comment]
@erezhdd Any updates on this?

**Comment by erezhdd** [comment]
Of what I can observe, automatic reconnection doesn't work most of the time, even with version 5.0.0. One issue I have right now, is that I click on "Show PB for desktop" and get a completely-gray window. Seems to me that the connection with PB got stalled some time ago, and when connectivity was resumed, the window should have been refreshed.
Is there a log of events (connect/disconnect/reconnect) that I can check and possibly send back to you for analysis?

**Comment by sidneys** [comment]
@erezhdd 

Of course there is. First launch the app in DEBUG mode, which gives you enhanced logs and interactive debugging tools:

```bash
DEBUG=1 pb-for-desktop
```

The logs are then located in:
```
$HOME/.cache/pb-for-desktop/log/pb-for-desktop.log
```

Thanks for your contribution & happy easter!

**Comment by sidneys** [comment]
@erezhdd  Any updates on this?

**Comment by erezhdd** [comment]
Trying 5.9.4 today. Will update.

So far, automatic reconnection did not work properly, in the sense that resuming the laptop resulted in a frozen app that needed to reconnect manually again to resume (thanks for implementing the manual button!). 
I did not check what the reconnect implementation is, but assuming it's a ping-to-pushbullet, I believe I can speculate the cause: such a ping will not detect an issue with a hung-up TCP connection, even if the ping is  TCP based (http-ping). The reason is that the ping should likely start a fresh TCP connection every time, and will therefore work after laptop/network resume, failing to detect an issue. 
I can suggest two ways to resolve this (assuming 5.9.4 still has this issue and my assumption about implementation is correct):
1. Make the ping detection part of the main connection. In other words, in order to ping pushbullet, just issue a REST call to the service using the main connection to it, but put a timeout on the REST call. If the timeout expires before receiving a reply, then that's a disconnection. The ping should be periodical.
2. Hook up the OS events of suspend/resume for network and laptop to detect disconnections.
I think that solution 1 is probably the easiest, most reliable and portable of the two.

**Comment by erezhdd** [comment]
As expected, 5.9.4 has the same reconnection issue - it misses on detecting network and laptop disconnections. See the discussion in the previous post.

**Comment by aia832003** [comment]
I am seeing the same issue on 5.9.6 running on Fedora 26. The reconnect button is a nice touch but would be great if the reconnect would happen when connection resumes to the network. Let me know if I can help in any way and thanks for PB4D!

**Comment by sidneys** [comment]
This has been implemented for a while now, closing.
