### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by jimjam-slam** [sidneys/pb-for-desktop#28]
## 🤷🏽‍♂️ Current Behaviour

When I use 'sudo npm install --verbose -g pushbullet-desktop', I eventually get:

    npm verb stack Error: electron-prebuilt@1.4.13 postinstall: `node install.js`
    npm verb stack Exit status 1
    npm verb stack     at EventEmitter.<anonymous>    (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
    npm verb stack     at emitTwo (events.js:106:13)
    npm verb stack     at EventEmitter.emit (events.js:191:7)
    npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
    npm verb stack     at emitTwo (events.js:106:13)
    npm verb stack     at ChildProcess.emit (events.js:191:7)
    npm verb stack     at maybeClose (internal/child_process.js:850:16)
    npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
    npm verb pkgid electron-prebuilt@1.4.13
    npm verb cwd /Users/rensa
    npm verb Darwin 16.4.0
    npm verb argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "install" "--verbose" "-g" "pushbullet-desktop"
    npm verb node v6.1.0
    npm verb npm  v4.4.4
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! electron-prebuilt@1.4.13 postinstall: `node install.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the electron-prebuilt@1.4.13 postinstall script 'node install.js'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node install.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs electron-prebuilt
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls electron-prebuilt
    npm ERR! There is likely additional logging output above.
    npm verb exit [ 1, true ]
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/rensa/.npm/_logs/2017-03-22T02_47_21_151Z-debug.log
    npm verb code 1

## 🎯 Expected Behaviour

I expected the app to install without error.

## 👟 Steps to Reproduce (S2R)

 1. 'sudo npm install --verbose -g pushbullet-desktop'

## 🏡 Environmental Context

**App Version**
v0.0.1
**Installation Type** 
Setup
**Operating System**
macOS: 10.12.3
**Node**
v6.1.0
**NPM**
v4.4.4

**Comment by sidneys** [comment]
@rensa 
Thanks for your interest in this project. It has been renamed to `pb-for-desktop`.
We just added a deprecation notice within the legacy module.

Install the global npm module using:
```bash
sudo npm install --verbose --global pb-for-desktop
```

May i ask how you did find the old module name? Cheers!

**Comment by jimjam-slam** [comment]
@sidneys Ah, thanks! I found the old module name on [npmjs.com](https://www.npmjs.com/package/pushbullet-desktop) when I was Googling around for Pushbullet clients.

`pb-for-desktop` installs fine,  but it crashes when I run it (would you like me to open a separate issue?):

    $ pb-for-desktop
    module.js:440
        throw err;
        ^
    
    Error: Cannot find module 'electron'
        at Function.Module._resolveFilename (module.js:438:15)
        at Function.Module._load (module.js:386:25)
        at Module.require (module.js:466:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/pb-for-desktop/bin/cli.js:21:18)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:456:32)
        at tryModuleLoad (module.js:415:12)
        at Function.Module._load (module.js:407:3)

**Comment by sidneys** [comment]
@rensa 
Yes, please open a different issue. And feel free to use the precompiled release until the fix is in
