### ISSUE TITLE
Add support for "dismissal" push type

### ISSUE THREAD

**Issue by electronic-dk** [sidneys/pb-for-desktop#29]
Pushbullet send a push with "dismissal" type when a user dismisses a notification, it would be good to support it in PB for Desktop

## 🤷🏽‍♂️ Current Behaviour
"dismissal" pushes get ignored

## 👟 Steps to Reproduce (S2R)

1. Launch the app, log in
2. Send a notification, wait for it to appear on the computer
3. Dismiss it on the phone

**Comment by electronic-dk** [comment]
I have it working, although, it's impossible do dismiss notifications from the computer now, I'll submit a PR

**Comment by sidneys** [comment]
Implemented in [4.3.0](../releases). Please review, @electronic-dk.
