### ISSUE TITLE
Unable to extract ZIP file on OS X

### ISSUE THREAD

**Issue by bkromhout** [sidneys/pb-for-desktop#3]
Hi, for some reason OS X's Archive Utility app has some trouble working with the ZIP file for OS X (Darwin). When I attempt to extract it, this is the error dialog I get:
<img width="381" alt="screen shot 2016-08-30 at 6 19 51 pm" src="https://cloud.githubusercontent.com/assets/4447359/18109358/d2314202-6ede-11e6-97a6-a9915efb5257.png">

Moving the file to another directory doesn't solve the issue (so it isn't permissions), and I'm able to extract it successfully using third party apps such as The Unarchiver or BetterZip (so it isn't corruption).

**Comment by sidneys** [comment]
Thanks for the input! Updated the release, please re-check.

**Comment by sidneys** [comment]
@bkromhout New versions directly provide dmg/deb/exe binaries without the zip wrappers, closing the issue.
