### ISSUE TITLE
Push notifications on Mac show "push.title"

### ISSUE THREAD

**Issue by dbalatero** [sidneys/pb-for-desktop#32]
## 🤷🏽‍♂️ Current Behaviour

When I receive a notification in Notification Center on Mac, I see `push.title` in the notification title which looks like a bad template replacement string.

<img width="323" alt="screenshot 2017-03-23 10 32 56" src="https://cloud.githubusercontent.com/assets/59429/24261530/80cb39e6-0fb4-11e7-9a9a-8cc023030753.png">

## 🎯 Expected Behaviour

I'd expect to see an actual title related to the notification.

## 👟 Steps to Reproduce (S2R)

 1. Receive any push notification on OS X.
 1. Should see the `push.title` bug.

## 🏡 Environmental Context

**App Version**
v4.3.0
**Installation Type** 
Setup
**Operating System**
Mac Sierra 10.12.3

**Comment by sidneys** [comment]
@dbalatero 
Great find! As we do not use mirroring often, the testing here is somewhat spotty. Title should only contain the application name, whereas the body of the notification should contain the notification itself.

This is fixed in v4.3.2, please review and comment

**Comment by jimjam-slam** [comment]
Also seeing this in v4.3.0 on macOS 10.12.3

**Comment by sidneys** [comment]
@rensa 
The change was pushed to v4.5.1, which is [available now, please review](../releases). The mirrored icon should also show.

**Comment by jimjam-slam** [comment]
v4.5.1 appears to fix #32 :)

**Comment by dbalatero** [comment]
@sidneys works for me, thanks for the quick fix 👍

**Comment by sidneys** [comment]
@dbalatero Glad to help.
