### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by volt4ire** [sidneys/pb-for-desktop#35]
Would you consider adding keyboard shortcuts (e.g.: for showing/hiding PB for Desktop, switching to the SMS or notifications tab, etc.) to the features roadmap? Thanks!

**Comment by sidneys** [comment]
@volt4ire 

This is doable, but as i don't use keyboard shortcuts on Pushbullet, it would require that you supply a baseline list of actions and keyboard shortcuts first.

Just add it to this issue.

**Comment by sidneys** [comment]
@volt4ire Closing this issue as you supplied no further input after 2 weeks.
Add a comment if the issue should arise again.

**Comment by hsanchez94** [comment]
I've thought of some cool shortcuts. I think for starters we could have:

CMD + Shift + S: SMS, Shortcut to go to SMS section.
CMD + Shift + D: Devices, Shortcut to go to Devices section.
CMD + Shift + P: Pushbullet, Show PB for Desktop / Bring to front

FYI: I'm on MacOS Sierra
