### ISSUE TITLE
Chatheads for conversations

### ISSUE THREAD

**Issue by domsle** [sidneys/pb-for-desktop#36]
Would it be possible to implement chathead-like feature?
Just like it is working in Facebook's Messenger, or official Pushbullet program.

**Comment by sidneys** [comment]
@domsle This would require porting the existing Chat Heads feature from the Chrome extension or a complete implementation, which is not planned for the scope of this project. A reason for this is that 1-to-1 chat (direct messaging) is the function which would benefit primarily from this feature - and pushbullet is only rarely used as a direct messaging platform.

But we are of course accepting pull requests. ;-)
