### ISSUE TITLE
Link pushes show title instead of body

### ISSUE THREAD

**Issue by jimjam-slam** [sidneys/pb-for-desktop#37]
## 🤷🏽‍♂️ Current Behaviour

I'm using an R package called [RPushbullet](https://cran.r-project.org/web/packages/RPushbullet/index.html) for API access. Whether I make a text-only push or a push with a link, it appears correctly on my phone (the package is configured to send pushes to all devices):

![screenshot 2017-03-29 13 11 20](https://cloud.githubusercontent.com/assets/6520659/24435494/5f515ff8-1481-11e7-8e5c-624587c0c2e8.png)

![screenshot_20170329-130849](https://cloud.githubusercontent.com/assets/6520659/24435624/31247ca4-1482-11e7-852f-e3d2c19d4364.png)

But on PB for Desktop, the link push has the title as both the title and the body:

![screenshot 2017-03-29 13 11 34](https://cloud.githubusercontent.com/assets/6520659/24435524/80c0de48-1481-11e7-838e-daf25be8335c.png)

The notification works as expected when clicked on, opening my browser to the pushed URL.

## 🎯 Expected Behaviour

I expected that the title and body would both be visible in the mirrored notification with the link.

## 👟 Steps to Reproduce (S2R)

 1. Install and configure [Rpushbullet](https://cran.r-project.org/web/packages/RPushbullet/index.html).
 2. Send a link push: `pbPost('link', title = 'Sup?', body = 'Hey there', url = 'http://rensa.co')`

## 🏡 Environmental Context

**App Version**
v4.7.5
**Installation Type** 
Setup
**Operating System**
macOS 10.12.3

**Comment by sidneys** [comment]
@rensa 

Please test this issue again with the latest version. --> [Link](../releases)

**Comment by jimjam-slam** [comment]
Looks good in v4.9.1!

<img width="334" alt="screenshot 2017-04-02 10 37 40" src="https://cloud.githubusercontent.com/assets/6520659/24583529/7cd82d42-1790-11e7-81fc-ff79a9ca4d23.png">
