### ISSUE TITLE
Android sms native notifications not showing on macOS

### ISSUE THREAD

**Issue by agrancho** [sidneys/pb-for-desktop#38]
**Hi guys!!** Thanks for this app, expecting this for a while now great job 👍 👍 
But I'm having an issue, that it's kind of a deal breaker... 
Hope it can be fixed, thanks! 😃 

##

## 🤷🏽‍♂️ Current Behaviour
I setup the app on my macOs and everything went smoothly. I can receive native macOS notifications from WhatsAPP, Instagram, Slack, etc... Except SMS!
When i receive a SMS it doesn't trigger a notification on my mac, but when I go to the PB for desktop I can see he received it in the SMS section. 
When I receive WhatsAPP notification for instance, he triggers the native notification as expected but not whit SMS. 
**When I send a SMS through the APP it goes well, and vice versa.. but no notification on my mac at all!**

## 🎯 Expected Behaviour
When I receive a sms I should be able to receive a native notification on my macOS with the sms content. 

## 👟 Steps to Reproduce (S2R)
 1. Receive a text on my android
 2. Wait for notification on mac (which don't show)
 3. Open desktop app and verify if sms reached pushbullet
 3. Sms reached on app but din't showed by native notification.

## 🏡 Environmental Context
**App Version**
v4.7.5
**Installation Type** 
Download of the .dmg file from the website
**Operating System**
macOs Sierra, v10.12.3 (16D32)

**Phone used**
Moto G 1st Generation
**SMS App used**
Google Messenger or SMS/MMS v.5.1.2 (tried on booth)

**Comment by nemonein** [comment]
It's the same in the Ubuntu 16.04. SMS notification does not work at all.

**Comment by sidneys** [comment]
@nemonein 

Please test this issue again with the latest version. All mirroring tests were conducted successfully so far --> [Link](../releases)

**Comment by nemonein** [comment]
@sidneys Finally, it works.(v. 4.9.1).
How ever, there's an error during the start up. (#39 )

**Comment by sidneys** [comment]
@nemonein 
Thanks for the feedback. As it was only tested on virtually devices, would it be possible for you to add a screenshot with the working SMS feature?

The new issue is tracked in #39.

**Comment by nemonein** [comment]
@sidneys 
Thank you for your effort.
Here's the screen shot.
![pb-for-desktop](https://cloud.githubusercontent.com/assets/5688288/24587954/578b4e10-17fa-11e7-9786-3c5d7eb6c288.jpg)

But, I've found another problem.
It ONLY works when Google chorme is not running, where I installed [pushbullet web app](https://chrome.google.com/webstore/detail/pushbullet/chlffgpmiacpedhhbkiomidkjlcfhogd?utm_source=chrome-app-launcher-info-dialog), and I had disabled notifications for chrome app.
When chrome is running, pb-for-desktop does not show SMS notifications. I'm not sure, but I think it does some other app's notifications.

I both installed pb-for-desktop and pushbullet for chrome. I only turned on the notification on pb-for-desktop.

**Comment by sidneys** [comment]
@nemonein 
Thanks for the screenshot! About Chrome: Interesting. Please create a new issue for this problem.

**Comment by nemonein** [comment]
I tried 4.9.8, the problem I mentioned above(with Google chrome) is not appeared.
I don't know it's fixed, or maybe it was just my mistake.
I'll report if I find something.

Thanks again!

**Comment by agrancho** [comment]
@sidneys working here as well!! 🎊 

![captura de ecra 2017-04-03 as 11 02 58](https://cloud.githubusercontent.com/assets/14932142/24604625/6e3d33f4-185d-11e7-8645-5e554d7af550.png)

Regarding the issue with Chrome, not happening to me 😕 
Is there an option that allows the notification to have the text content hidden in the notification?

Thanks again for the quick fix and the great work! 👍

**Comment by samuelBB** [comment]
@sidneys I am experiencing this issue with the latest version of the app (6.7.7). I'm on MacOS High Sierra 10.13.2. SMS notifications don't show up at all (to be clear, the texts *do* come through onto my computer just no notifications). I verified that this is an issue with the app and not my phone/computer notification settings b/c the notifications work as expected on the previous stable version of the app (6.5.1). For now I will use this previous stable version. Relatedly, I don't get any badge notifications for the app (on 6.7.7 or 6.5.1). Are badge notifications supported?

**Comment by samuelBB** [comment]
@sidneys Disregard what I said about badge notifications, I simply didn't see the menu option *smacks forehead*.

**Comment by drew5494** [comment]
Sorry I seem to be having this issue with the latest version all notifications work except sms... :( 
Reverting back to the previous version solved the issue
