### ISSUE TITLE
[Ubuntu 16.10] Failed to run: 'Maximum call stack size exceeded' on startup

### ISSUE THREAD

**Issue by SolarLiner** [sidneys/pb-for-desktop#39]
## 🤷🏽‍♂️ Current Behaviour
On application startup, error dialog spawns with a 'Maximum call stack size exceeded' error, showing a call stack:
![screenshot from 2017-04-02 01-50-57](https://cloud.githubusercontent.com/assets/4302963/24583337/1ed80f6c-1747-11e7-8c8b-c1edf4c37060.png)

After this, notifications show up, but the main app cannot be shown nor the tray menu displayed.
## 👟 Steps to Reproduce (S2R)
Launch the app.

## 🏡 Environmental Context

**App Version**
v4.9.1
**Installation Type** 
amd64.deb
**Operating System**
Ubuntu 16.10 64bit - kernel 4.8.0-44-generic

**Comment by nemonein** [comment]
It's exactly the same in the Ubuntu 16.04. (v.4.9.1)

**Comment by sidneys** [comment]
@nemonein 
Please re-test with the [latest version](../releases) and share your results.

**Comment by SolarLiner** [comment]
Error dialog disappeared but neither the indicator menu nor the main app can be spawned still.

**Comment by sidneys** [comment]
@SolarLiner 

Can you do a full uninstallation before trying?

#### Remove
```bash
sudo dpkg -r pb-for-desktop
rm -rf ~/.config/PB\ for\ Desktop/
```

#### Install & Start
```bash
curl -O -J -L https://github.com/sidneys/pb-for-desktop/releases/download/v4.9.8/pb-for-desktop-4.9.8-amd64.deb
sudo dpkg --install --force-overwrite pb-for-desktop-4.9.8-amd64.deb
pb-for-desktop --debug
```

**Comment by SolarLiner** [comment]
![screenshot from 2017-04-02 23-18-50](https://cloud.githubusercontent.com/assets/4302963/24591148/ccb72a06-17fa-11e7-8378-b6a192e4260e.png)
Starting in debug mode greets me with two Developper panes, one of which constantly displaying errors on some ```setInterval()``` function.

Starting normally works fine, though.

**Comment by sidneys** [comment]
@SolarLiner

Thanks for that screenshot! What kind of desktop are you using on Ubuntu? I think it's related to that, as the app is running (the setinterval error is due to pushbullet not having logged in yet), but the menubar icon is invisible...

**Comment by nemonein** [comment]
There's no problem on the Ubuntu 16.04, and 16.10 with PB for Desktop v. 4.9.8. Both are the original version of Ubuntu(Unity).

**Comment by SolarLiner** [comment]
@sidneys Running on GNOME, the "legacy tray" (because the 'new' indicators are installable extensions) is that thing on the bottom left you can open by hovering over. The tray icon is there when running debug though.

Other than that, it works wonder now!

**Comment by sidneys** [comment]
@SolarLiner 
Glad to hear. This issue can be closed then?

**Comment by SolarLiner** [comment]
Yeah I'm closing it now.
