### ISSUE TITLE
Error message when clicking "Show Window"

### ISSUE THREAD

**Issue by mxywes** [sidneys/pb-for-desktop#4]
Hi, here to report this message:
![image](https://cloud.githubusercontent.com/assets/17968159/18225700/3936db2a-71f9-11e6-9580-a715990ba9a8.png)

Using Windows 10, when clicking on the Show Window label (note that the check mark still appears/disappears despite the message.
Occurs when enabling or disabling the option.

**Comment by sidneys** [comment]
@Mxywes thanks for the report, keep them coming.  The reported issue and lots of others have been fixed, as well as new features introduced, in the new version 2.0.0.

Please review, feedback is much appreciated.
