### ISSUE TITLE
Badge number for SMS

### ISSUE THREAD

**Issue by untyped1** [sidneys/pb-for-desktop#41]
Would it be possible to have badges on the dock icon or the status bar for unread SMS?

**Comment by sidneys** [comment]
@untyped1  Yes, good idea. A badge for all new unread pushes would be the best, wouldn't it?

**Comment by untyped1** [comment]
@sidneys I guess. I don't you use any other pushes except SMS. I am not sure how complex it will be to be able to control which ones show badges.

**Comment by sidneys** [comment]
This feature landed in [v5.4.0.](../releases). Please review & confirm.

**Comment by untyped1** [comment]
@sidneys Thanks for coming back so fast we a new update. I am not sure if I have to do something on my end, but I still don't see a badge number on the dock icon. Also, I don't see the badge notification configurator, where can that be found?

**Comment by untyped1** [comment]
@sidneys I see the option for "unread Count" now, but still doesn't seem to be functioning on my end.

**Comment by untyped1** [comment]
@sidneys I played it with it a little bit and this is what I noticed. If you have it running in the background and you receive a new text it will not register the badge. If you restart, it would show a badge and as soon as you open SMS it will disappear which is the way it should be. But if you restart it again and even if you do not have any new text it will show a badge.

**Comment by sidneys** [comment]
@untyped1 Thanks for the detailed report. The feature has been updated as of [v5.4.1, please update](../releases).

**Comment by sidneys** [comment]
@untyped1 Online now.

**Comment by untyped1** [comment]
@sidneys Thanks for the update. I am still not seeing it functioning correctly. The only difference I see now is in the badge count. On 5.4.0 I had 3 everytime I restart it and now on 5.4.1 is 1. I still don't see a badge count when receiving push in the background.

**Comment by sidneys** [comment]
@untyped1 Thanks for the feedback, i think we nailed the issue now. Pushing a hotfix within the hour.

**Comment by sidneys** [comment]
@untyped1 

Does this issue still occur in [v5.4.4](../releases)?
Will close otherwise.

**Comment by untyped1** [comment]
@sidneys Looks like there is progress 👍 Now I definitely receive a count badge when a new text arrives! When I go check out the message it does not clear it though. Also when I restart the PB for desktop there is a badge count again even though I have read all texts. FYI I do not use the notification mirroring option, so it should not be a push from another app that I haven't checked. Badge count issues aside now, PB for desktop marks my texts as pending when I try to send one. I will attach a screenshot. They do send and I receive, but they pile up as pending. 
<img width="312" alt="screen shot 2017-04-09 at 12 10 13 pm" src="https://cloud.githubusercontent.com/assets/24485389/24840192/8df7609c-1d1d-11e7-8619-5bbffd6dbdce.png">

**Comment by sidneys** [comment]
@untyped1 Thanks for the feedback. I'll close this issue for now, as the `pending` issue is tracked here: #43 

If problems relating to the badge remain, please add a comment.

**Comment by samuelBB** [comment]
@sidneys I am still experiencing the badge issues described in @untyped1's last message in this thread. Specifically, I can see the badge count (from unread SMS), but the badge count does not clear when I navigate back to the app (which has the SMS conversation open with the unread messages). The only way I have successfully cleared the badge count is by clicking and navigating away from the "SMS Texting tab" in the app, and going to one of the other sections of the app, e.g., "Devices" or "Following". Just switching SMS conversations or responding to the current conversation does not clear the badge count. I am using the latest version of the app (6.7.7). On a Macbook Pro macOS High Sierra 10.13.2.
