### ISSUE TITLE
Stuck on connecting screen

### ISSUE THREAD

**Issue by grantsteele** [sidneys/pb-for-desktop#42]
I'm running PB 5.4.0 on macOS 10.12.4 and it's stuck at the "connecting" screen.

I've also run into the same problem in Windows 10 Pro (64) Version 1703 build 15063.13.

I had signed up to Pushbullet for the first time today using my Google credentials and have installed the official Chrome browser extension on each OS before installing PB for Desktop.

Any ideas?

**Comment by sidneys** [comment]
@grantsteele 

Thank you for the heads up – this is a very important issue (regression). Updated version will be pushed within the hour.

**Comment by sidneys** [comment]
@grantsteele 
Online now, please review: [v5.4.1, please update](../releases)

**Comment by bigjv12** [comment]
New version logged in perfectly thank you

**Comment by sidneys** [comment]
@bigjv12 @grantsteele Thanks, closing.

**Comment by grantsteele** [comment]
Yep, I can confirm it's working now. Thank you!
