### ISSUE TITLE
linux tray icon almost invisible on transparent or black top bar in gnome

### ISSUE THREAD

**Issue by subjectdenied** [sidneys/pb-for-desktop#47]
## 🤷🏽‍♂️ Current Behaviour

tray icon is invisible or almost not visible when using black or translucent (by extension) top bar in gnome 3.24

## 🎯 Expected Behaviour

icon should be visible either color white, or previous behaviour
## 👟 Steps to Reproduce (S2R)

install latest (5.9.1) release (started with 5.8.1 for me)
## 🏡 Environmental Context

**App Version**
v5.x
**Installation Type** 
archlinux aur package
**Operating System**
Archlinux, Gnome 3.24

**Comment by SolarLiner** [comment]
I'm the one behind the change. I'm also using GNOME 3.24 under Ubuntu.

Using TopIcons Plus you can set brightness all the way to 1.0 to set all icons to white. Meanwhile I'll PR a change of colors, because most DE have dark themed bars. It's just a matter of changing the color though.

**Comment by subjectdenied** [comment]
thanks for fast respone and the hint about brightness setting in top-icons-plus (which i'm using), however this distorts other color icons i'm using

**Comment by SolarLiner** [comment]
Another possibility while waiting could be [Hardcode-tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) but I'm not sure if they updated their release version to work with PB for Desktop.

**Comment by SolarLiner** [comment]
Submitted PR #48 to change them to white.
