### ISSUE TITLE
Universal clipboard isn't bidirectional

### ISSUE THREAD

**Issue by anna-is-cute** [sidneys/pb-for-desktop#49]
## 🤷🏽‍♂️ Current Behaviour

Copying text on another device should update the clipboard on the device PB for Desktop is running on.

## 🎯 Expected Behaviour

Text copied on the desktop using PB for Desktop is sent to other devices, but not vice versa.

## 👟 Steps to Reproduce (S2R)

1. Select text on a different device with Pushbullet, such as a phone.
2. Copy or cut that text.
3. Try to paste it on the device running PB for Desktop.

## 🏡 Environmental Context

**App Version**
v5.9.2
**Installation Type** 
App
**Operating System**
macOS 10.12.5 Beta

Using end-to-end encryption, as well, which Pushbullet reports PB for Desktop is not using, which could be part of the problem (or the entire problem).

![not encrypted](http://i.imgur.com/3yCa9iZ.png)

**Comment by sidneys** [comment]
@jkcclemens 

This issue has been addressed in previous versions and cannot be reproduced anymore. Should it reoccur, please create a new ticket.

Cheers,
S
