### ISSUE TITLE
Can not install ubuntu 16.04 amd64

### ISSUE THREAD

**Issue by patricklibert** [sidneys/pb-for-desktop#5]
sudo dpkg -i ./pb-for-desktop-linux-x64-v2.1.0.deb 
[sudo] password for redman: 
dpkg: error processing archive ./pb-for-desktop-linux-x64-v2.1.0.deb (--install):
 package architecture (x64) does not match system (amd64)
Errors were encountered while processing:
 ./pb-for-desktop-linux-x64-v2.1.0.deb

**Comment by philborman** [comment]
Note to maintainer:
Debian packages should be amd64 not x64
and i386 not ia32

**Comment by ryanleesipes** [comment]
Same here.

**Comment by ledshark24** [comment]
hi,
same here.

**Comment by canalet0** [comment]
Joe from omgubuntu.co.uk repacked the .deb. you can acess the .deb searching by his comment on http://www.omgubuntu.co.uk/2016/09/app-to-get-android-push-notifications-on-ubuntu-desktop

**Comment by sidneys** [comment]
@redpop1 , @philborman @ledshark24 & @canalet0  - thanks for your feedback. I could reproduce the issue.

The .deb  package is built via CI (see travis.yml), so there seems to be an issue with the build configuration / build matrix. Those issues will be dealt with in the next minor release at the latest - of course, pull requests are welcome :-)

Thanks for the bug report.

**Comment by sidneys** [comment]
@redpop1 Please re-test with version 2.2.1, which should fix the architectures issue.

**Comment by mhalano** [comment]
@sidneys  @redpop1 Works fine, even the name file is a little mess IMHO. The file name shpuld be:
pb-for-desktop_2.2.1_amd64.deb
pb-for-desktop_2.2.1_i386.deb
Once is a Debian package there is no need to explain is a Linux version (because Debian packages is only available for Linux).

**Comment by patricklibert** [comment]
works fine

**Comment by sidneys** [comment]
@mhalano Thanks for the suggestion, naming schemes have been amended.
