### ISSUE TITLE
Action Buttons for Notifications

### ISSUE THREAD

**Issue by hsanchez94** [sidneys/pb-for-desktop#51]
## 🤷🏽‍♂️ Current Behaviour

So as of now, whenever you get an SMS notification, the Mac notification pops up as a banner. 

## 🎯 Expected Behaviour

It would be cool if you could reply to the sms notification right from the banner like so:
![example](https://cloud.githubusercontent.com/assets/10713962/25651575/cffd6f58-2fb1-11e7-9358-8dd0a0bbd3f4.jpg)

## 👟 Steps to Reproduce (S2R)

 1. Receive an SMS message
 2. Highlight banner with mouse
 3. Select Reply
 3. Type Response and voila!

## 🏡 Environmental Context

**App Version**
v5.9.2
**Installation Type** 
Setup
**Operating System**
MacOs Sierra

**Comment by sidneys** [comment]
@hsanchez94 

This feature has been added since 6.1.6. Please add your feedback.

Cheers, S
