### ISSUE TITLE
High battery usage when waking from sleep (macOS)

### ISSUE THREAD

**Issue by ghost** [sidneys/pb-for-desktop#52]
## 🤷🏽‍♂️ Current Behaviour

PB is set to start up upon login, and does so correctly. However, when I put my Mac to sleep and wake it a few minutes later, the PB app has closed (by design?) and starts again - the dock icon appears briefly and the tray icon reappears. From then on, 'PB for Desktop' appears constantly as 'Using Significant Energy'. In the Activity Monitor, it shows an Energy Impact of between 14-16 even though I am not using the app. Closing and restarting the app (even force-quitting and restarting) does not help and the app still shows 14-16 energy impact. Only restarting macOS restores the app to its usual energy-efficient state.

## 🎯 Expected Behaviour

No significant energy impact should be evidenced after waking the app from sleep.

## 👟 Steps to Reproduce (S2R)

1. Put Mac to sleep.
2. Wait a few minutes.
3. Start Mac.
4. PB for Desktop starts upon waking the Mac from sleep.
5. Activity Monitor shows significant energy use by PB for Desktop.

## 🏡 Environmental Context

**App Version**
v5.9.2
**Installation Type** 
Setup
**Operating System**
macOS Sierra. 10.12.4, tMBP/Radeon460
<img width="798" alt="screen shot 2017-05-09 at 18 45 08" src="https://cloud.githubusercontent.com/assets/15131665/25864939/2180834c-34e9-11e7-8626-30bdcba73975.png">

**Comment by ghost** [comment]
Following further investigation, it appears that after waking from sleep there are **two** 'PB for Desktop Helper' processes, one of which is causing the energy impact spike. After quitting that process, PB for Desktop operates normally with the remaining Helper process at a low energy impact. Looks like the app is starting itself up twice after waking up from sleep...?

**Comment by ghost** [comment]
I can confirm that this issue is still there in version 5.9.6.

**Comment by sidneys** [comment]
@ShintoPlasm 

Does this issue still occur in the latest release?

Cheers,
S

**Comment by sidneys** [comment]
yy

**Comment by dam3313** [comment]
I confirm that the issue is still present in V6.5.1
![capture d ecran 2017-11-19 a 12 28 14](https://user-images.githubusercontent.com/22203969/32990186-2d08a08a-cd25-11e7-981e-ae97e63829ee.png)

**Comment by dam3313** [comment]
It seems that the app (V6.5.1) energy impact is between 20-24 after a sleep and wake-up but just for few seconds (during the reboot of the app) and after the energy impact go back to 0.

**Comment by sidneys** [comment]
@ghost
@dam3313 

That behaviour seems rather normal, or not outside of expected performance boundaries.
If this behaviour should worsen, please create a new ticket.

Cheers,
S
