### ISSUE TITLE
A queue of missed but still valid events

### ISSUE THREAD

**Issue by erezhdd** [sidneys/pb-for-desktop#53]
Ubuntu 16.04, PB4D 5.9.4
Once the app reconnects, how can I view events that are still shown on the phone but were missed by me, e.g., when the laptop was suspended? Does the PB service provide support for that?

**Comment by pongraczi** [comment]
Hmmm, is it the same as I reported some minutes ago?  
#66

**Comment by erezhdd** [comment]
Yes, sort of.. your item is more detailed and discusses the general case of missing out messages, so I think I would close this one as a duplicate of #66. Up to Sidney's decision.

**Comment by sidneys** [comment]
@erezhdd @pongraczi 

This indeed is a duplicate of #66, closing.
