### ISSUE TITLE
Show the app when double clicking the tray icon [on linux]

### ISSUE THREAD

**Issue by atleta** [sidneys/pb-for-desktop#57]
Hi,

This is not a bug, but a feature request, but I'll still use your template:

## 🤷🏽‍♂️ Current Behaviour
In order to open the app, one has to right click the tray icon to open the menu, then left click the first menu item to show the window. As I'm writing this, the tray icon has just stopped reacting to right clicks and it's not possible to open the app anymore.

## 🎯 Expected Behaviour
Double (left) click tray icon to open the window. Optionally: do it again to hide it.

## 🏡 Environmental Context
**App Version**
v0.0.1?
**Installation Type** 
Deb package
**Operating System**
Ubuntu 17.04

**Comment by atleta** [comment]
Maybe even using a single click (this is how slack works).

**Comment by sidneys** [comment]
@atleta

The underlying framework can currently reliable detect double clicks on tray icons. Hence, implementation of this feature has to wait until such time.

Cheers,
S
