### ISSUE TITLE
App should remember the last size and position

### ISSUE THREAD

**Issue by atleta** [sidneys/pb-for-desktop#58]
## 🤷🏽‍♂️ Current Behaviour
When you start the app, it will always start with a portrait layout of the same size, even if you have resized when running it the last time. (Note that the initial dimensions don't make sense anyway, since a large part of the content is not visible, only the menu fits in.)

## 🎯 Expected Behaviour
Remember the size (and maybe the position) of the window from the previous run.

## 👟 Steps to Reproduce (S2R)
Start the app, resize the app, quit the app and then start the app again.

## 🏡 Environmental Context

**App Version**
v5.9.6
**Installation Type** 
Deb package

**Operating System**
Ubuntu 17.04

**Comment by sidneys** [comment]
Hi @atleta 

This issue has been addressed in v6.1.6.
Looking forward to your feedback 😎.

Cheers, S
