### ISSUE TITLE
App doesn't show up in the task switcher

### ISSUE THREAD

**Issue by atleta** [sidneys/pb-for-desktop#59]
## 🤷🏽‍♂️ Current Behaviour
App doesn't show up in the task switcher (ALT-Tab)

## 🎯 Expected Behaviour
App should be present there

## 👟 Steps to Reproduce (S2R)
Open main window, press ALT-Tab, observe that the app icon is not there and thus not navigable (except for using the tray icon).

## 🏡 Environmental Context
**App Version**
v5.9.6
**Installation Type** 
Deb package
**Operating System**
Ubuntu 17.04

**Comment by capstan1** [comment]
For me it's in the dock and in task switcher under elementary OS Loki (based on Ubuntu 16.04).
Was it solved for you too?

**Comment by atleta** [comment]
Nope. Actually I stopped using it for now as it's mostly unusable as it is. Version of unity I'm using is 7.5.0 (7.5.0+17.04.20170407.1-0ubuntu1) that probably quite different from what you have, as they keep updating unity between releases and it indeed may be the source of the problem.

**Comment by sidneys** [comment]
@atleta 

Does this issue still occur in the latest release?

Cheers,
S

**Comment by sidneys** [comment]
@atleta

Closing this due to lack of required information.

Cheers,
S
