### ISSUE TITLE
Every time the app reconnects, it shows an old notification (always the same)

### ISSUE THREAD

**Issue by atleta** [sidneys/pb-for-desktop#60]
## 🤷🏽‍♂️ Current Behaviour
On every network reconnect event (whether it's after pulling out the network cable, reloading the app or starting the app) it shows a popup of an old notification. Probably originated from a facebook notification. And by old I mean it's at least several months old, while I have just installed the app a few hours ago.

## 🎯 Expected Behaviour
Not showing the same old notification again and again.

## 👟 Steps to Reproduce (S2R)
Make the app reconnect as described above.

## 🏡 Environmental Context
**App Version**
v5.9.6
**Installation Type** 
deb package
**Operating System**
Ubuntu 17.04

**Comment by sidneys** [comment]
@atleta

Closing this as it cannot be reproduced.

Cheers,
S
