### ISSUE TITLE
Use OS browser rather than internal browser for outh signup

### ISSUE THREAD

**Issue by studgeek** [sidneys/pb-for-desktop#61]
## 🤷🏽‍♂️ Current Behaviour
Currently when signing up using Google auth the user is prompted for their username/password from inside the app. I assume using an internal browser.
The problem with this is that the user can't tell if the password is being recorded.

## 🎯 Expected Behaviour
Instead, the app should launch the external browser with the oauth challenge and set it up to locally redirect back to the app when done.

That way the user can verify in the OS browser that connection is secure and they are really really giving their password to Google.

## 🏡 Environmental Context
**Operating System**
macOS 10.12.5 (16F73)

**Comment by sidneys** [comment]
@studgeek 

This feature would require a significant amount of engineering without carrying comparable benefits in terms of security, as bad webview-based application actor could still spy on user data in numerous other malevolent ways. Thus, this request cannot not be implemented currently.

However, why not submit a pull request? 😇

Cheers,
S
