### ISSUE TITLE
Show pb-for-desktop with a command?

### ISSUE THREAD

**Issue by alexhulbert** [sidneys/pb-for-desktop#63]
Hi! Is there any way I could show the pb-for-desktop window with a command? I'd rather not have the PB icon cluttering up my tray. Modifying the source code of pb-for-desktop to remove the tray icon was simple enough, but I'm not sure how I'd go about showing the actual window with an external command. Could someone familiar with electron and/or this program please guide me in the right direction?

Regards,

Alex Hulbert

**Comment by sidneys** [comment]
@Taconut 
Thanks for the input. Is this Windows or macOS-related? (please use the issue template in the future ;-) )

**Comment by alexhulbert** [comment]
Sorry for not following the issue template. I'm having this issue on Linux.

**Comment by ian-howell** [comment]
Hey Taconut, not sure if you've solved this issue yet, but it seems like the program can be started from the command line with `pb-for-desktop`

**Comment by alexhulbert** [comment]
@ian-howell That just populates the tray. i actually want to open and close the window with a command

**Comment by touste** [comment]
I second this request. I'm using a tiling window manager without tray display. Thanks!

**Comment by sidneys** [comment]
Hi @Taconut, @ian-howell, @touste 

This issue has been addressed in v6.1.6: Running `pb-for-desktop` if the application is already running will focus the application and restore all windows.

Looking forward to your feedback 😎.

Cheers, S
