### ISSUE TITLE
Package as a snap

### ISSUE THREAD

**Issue by peterhavener** [sidneys/pb-for-desktop#64]
## 🎯 Expected Behaviour

Make this awesome app available as a snap to be even more cross-distro compatible. I'm not a developer or packager, but from what I do know its fairly straight forward to build from a GitHub repository as detailed here: https://build.snapcraft.io/

## 🏡 Environmental Context

**App Version**
v5.9.6
**Installation Type** 
Setup
**Operating System**
Linux

**Comment by LyzardKing** [comment]
The PR #93 works.
It shouldn't need any more work than that, but it does need some testing
