### ISSUE TITLE
Viber calls sends a push every second

### ISSUE THREAD

**Issue by exarus** [sidneys/pb-for-desktop#65]
When I am on a Viber call I receive a notification to my Elementary OS (Ubuntu-based Linux) every second about being in a call.

## 🤷🏽‍♂️ Current Behaviour
I receive notifications each second during being on a call.

## 🎯 Expected Behaviour
I expect to receive notification when somebody calls me. 
Optionally I might receive notifications when I call somebody myself or when the call is finished.

## 👟 Steps to Reproduce (S2R)
1. Make sure PB for Desktop is connected with phone
2. Make a Viber call from the phone.
3. Check the notification on your Desktop.

## 🏡 Environmental Context
**App Version**
v5.9.6
**Installation Type** 
`deb` package installation via 
```bash
sudo dpkg -i *.dep
sudo apt install -f
```
**Operating System**
Elementary OS Loki (0.4.1)

**Comment by sidneys** [comment]
@exarus 

This issue currently cannot be reproduced, closing for now.

Cheers,
S
