### ISSUE TITLE
There is no Notification which contains all previous notifications, similar to chromium extension

### ISSUE THREAD

**Issue by pongraczi** [sidneys/pb-for-desktop#66]
## :speech_balloon:  Current Behaviour

When PB pushes a notification from any application from a mobile device (android), the notification appears in a popup. That's ok.
But there is no chance to see these notifications again if I missed one. I do not see any history of notifications.
In contrast, the PB extension for Chromium has a dedicated Notification tab, where I can see the history, all previous notifications.
I have an API where my Zabbix used to send me notifications about issues etc. and I only can see them when they pop up and I found no way to check the history.

## 🎯 Expected Behaviour

The PB4D should include a history panel, called Notifications where one could see all previous notifications, very similar to Chromium extension.
I prefer PB4D as a standalone application than Chromium extension.

## 👟 Steps to Reproduce (S2R)

 1. Wait for a notification from a mobile device, like Google Play update an application.
 2. A popup notification should appear in PB4D.
 3. Try to find the disappeared notification in the PB4D (I found nothing).

## 🏡 Environmental Context

**App Version**
v6.0.7
**Installation Type** 
from amd64.deb
**Operating System**
Linuxmint 18.x

**Comment by sidneys** [comment]
@pongraczi @erezhdd

This feature would require an implementation of a local notification queue, a feature which would defy the straightforward implementation of the app as a wrapper of the web application. Thus it is currently not within the scope of this app.

Cheers,
S
