### ISSUE TITLE
Automatic reconnect fails after waking up from sleep

### ISSUE THREAD

**Issue by bjptwist** [sidneys/pb-for-desktop#68]
I'm using version v6.2.6 and I've noticed an issue causing the app to fail to reconnect when I wake up computer from sleep. Basically if I put the computer into sleep mode, as soon as it wakes up, I have to restart the app in order to be able to reconnect (automatic reconnect its not working).

This was working fine in 6.1

**Comment by sidneys** [comment]
@bjptwist 
Cannot reproduce this. Works perfectly on my System (10.13 High Sierra), is there anything special to the context or circumstances (e.g., how was sleep/resume induced) which could be helpful in tracking this down? Thanks for your contributions 👍

**Comment by bjptwist** [comment]
Does not happen all the time. I'm using 10.12.6 (El Capitain). The sleep process is quite nomral, I just close de computer's lid and when I open it again, sometimes the application is not able to reconnect properly. If I open the app the green screens stays forever. Is there any way of extracting some debug info from the app?

**Comment by sidneys** [comment]
@bjptwist 

Thanks for the info. Extracting additional info works like this:
 1. Restart the app in debugging mode by selecting the menu entry (top left application menu) starts collecting additional app events
 1. Open the Logs file (also in the top left menu) after reproducing the error

**Comment by bjptwist** [comment]
@sidneys  I've sent you the logs via email.

**Comment by bjptwist** [comment]
Sorry for pushing this, but do you have any update on this issue?

**Comment by sidneys** [comment]
@bjptwist 

We just tested this with v6.7.7 on macOS High Sierra (MacBook Pro). After resuming from sleep, the app restarts and shows all notifications as usual. All logged events were similar to the log file you provided, showing nominal operation. 

Does this issue still persist on your system?

Kind regards,
S
