### ISSUE TITLE
pb-for-destop crashes immediately upon opening

### ISSUE THREAD

**Issue by typical-earthling** [sidneys/pb-for-desktop#69]
## 🤷🏽‍♂️ Current Behaviour
When attempting to run pb-for-desktop the window opens for a fraction of a second and then disappears. This is happening with the .deb package as well as the Appimage. Strangely, a process for the app does appear in my task manger.

## 🎯 Expected Behaviour
pb-for-desktop should start.

## 👟 Steps to Reproduce (S2R)
Attempt to start the application by clicking on the icon in my applications menu, or, in the case of the Appimage, by clicking on the Appimage file after installation.

## 🏡 Environmental Context
**App Version**
v0.0.1

**Operating System**
Kubuntu 17.04 64-bit with KDE Plasma 5.9.5

-----

Any tips would be appreciated. Forgive me if I left out any key information, I'm relatively new to Linux. I can provide more details if necessary.

Thanks!

**Comment by sidneys** [comment]
@typical-earthling 

Could not reproduce this on on the documented platform and using the latest release. If this issue should reoccur, please create a new issue.

Cheers,
S
