### ISSUE TITLE
A JavaScript error occurred in the main proccess

### ISSUE THREAD

**Issue by zmni** [sidneys/pb-for-desktop#7]
Windows 10 x64
PB for Desktop x64

This is happened when I click on `Launch on System Startup` tray option.

![pb-for-desktop](https://cloud.githubusercontent.com/assets/841523/18739471/11e6ecde-80ce-11e6-9ecf-84d1ec9740b5.jpg)

Update: Also happened when I disable that option.

![pb-for-desktop2](https://cloud.githubusercontent.com/assets/841523/18740650/fcb91984-80d4-11e6-9fb7-7785dafed27c.jpg)

**Comment by sidneys** [comment]
Hi @zmni, this bug has been fixed recently. Could you please re-test it with version 2.4.0+?

kind regards

**Comment by zmni** [comment]
Everything work as expected now. No error, no weird thing. Thanks.
