### ISSUE TITLE
Notification Mirroring doesnt work

### ISSUE THREAD

**Issue by bin101** [sidneys/pb-for-desktop#70]
## 🤷🏽‍♂️ Current Behaviour

Since version 6.3.1 I dont receive any mirrored Notifcation from my phone. The snooze notification for example still works. The Archlinux User Repository currently only have version 5.9.2 (which works fine) and I tested all versions from 6.3.1 to 5.9.2. Only version 6.3.1 has this issue.

## 🏡 Environmental Context

**App Version**
v6.3.1
**Installation Type** 
manual aur package installation via makepkg.
I used this [(aur-link)](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pb-for-desktop) PKGBUILD, exchanged the version with 6.3.1 and skipped the checksum check.
**Operating System**
Arch Linux
uname -a
Linux T430 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux

**Comment by sidneys** [comment]
@bin101 

Thanks for the report. The fix for this issue is slated be contained in the next release.

**Comment by erezhdd** [comment]
Same problem here. Ubuntu 16.04.3.

**Comment by erezhdd** [comment]
More on Ubuntu 16.04.3 + PB4D 6.3.1 - also tried to reset the configuration first. Same issue - no notifications.

**Comment by sidneys** [comment]
@bin101 @erezhdd 

Please review this issue with the latest release: https://github.com/sidneys/pb-for-desktop/releases

**Comment by erezhdd** [comment]
Tried 6.5.0 with Ubuntu 16.04.3. Still no notifications (even after configuration reset and sign-in again). 
Even worse - no SMS in the PB window!
May I suggest that in the next release a menu item is added for reporting issues (link to github issues)?

**Comment by bin101** [comment]
@sidneys I can confirm that notification mirroring still doesnt work but I cant confirm @erezhdd sms problem.

**Comment by erezhdd** [comment]
sms problem turned out to be a bug of PB app on Android. 
It seems that the last working version of PB4D with mirroring is 6.2.6 ("Stitch"?) so sticking with it.

**Comment by erezhdd** [comment]
Ubuntu 16.04.3 - version 6.5.1 works great! Thanks!

**Comment by bin101** [comment]
Still doesn't work for me. I use i3 as window manager.

Not every linux system uses Unity, so why do you hard set it?:
```js
if (platformTools.isLinux) {
    process.env.XDG_CURRENT_DESKTOP = 'Unity';
}
```

**Comment by bin101** [comment]
Got it working. You only mention libnotify as linux dependency in your README but I also installed notify-osd now and it works now.

**Comment by sidneys** [comment]
@bin101 

Thanks for your perseverance. Closing for now.

Cheers,
S
