### ISSUE TITLE
Repo does not have a Release file

### ISSUE THREAD

**Issue by RayBB** [sidneys/pb-for-desktop#71]
## 🤷🏽‍♂️ Current Behaviour
When I run: `sudo apt update`

I get the error:

> E: The repository 'https://packagecloud.io/sidneys/pb-for-desktop/linuxmint sonya Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

## 🏡 Environmental Context

**App Version**
Latest
**Installation Type** 
Installation via package manager (Linux)
**Operating System**
Linux Mint 18

**Comment by sidneys** [comment]
@RayBB 

Thanks for the report. The repository url will change soon, the current one is not working as expected.

**Comment by sidneys** [comment]
@RayBB 

The package manager installation feature is scrapped for the foreseeable future due to lack of capable deployment providers for FOSS projects, packagecloud didn't cut it. If you have an alternative proposal, feel free to create a new ticket.

Cheers,
S
