### ISSUE TITLE
No pushes show in Windows 10 Action Center

### ISSUE THREAD

**Issue by judgeito** [sidneys/pb-for-desktop#74]
## 🤷🏽‍♂️ Current Behaviour

Just installed for the first time. Connected everything as it should be. No test pushes show up in Windows 10 Action Center -- I only hear the default *ding*
This behavior persists after a system restart

## 🎯 Expected Behaviour

You advertise "fully native notifications" and I expected it.

## 👟 Steps to Reproduce (S2R)

 1. Launch PB for Desktop
 2. Login
 3. Receive push
 4. No native notification, just audio *ding*

## 🏡 Environmental Context

**App Version**
v6.5.1
**Installation Type** 
exe Setup
**Operating System**
Windows 10 Home x64 1709 (16299.64)

**Comment by judgeito** [comment]
For what it's worth, no "PB for Desktop" entry appears in Windows' [Settings] > [System] > [Notifications & actions] > "Get notifications from these senders"

**Comment by sidneys** [comment]
@judgeito 

Thanks for your report. This issue is occurring on recent Windows 10 releases due to an upstream Electron issue (see https://github.com/electron/electron/issues/10864). However, a hotfix will be released shortly.

Cheers,
S

**Comment by sidneys** [comment]
@judgeito 

This issue has been fixed as of v6.7.7.

Cheers,
S
