### ISSUE TITLE
Feature Request: Disable Desktop Notifications

### ISSUE THREAD

**Issue by clutchwave** [sidneys/pb-for-desktop#75]
It would be fantastic if you could disable all desktop notifications, forever. I don't want popups when running `pb-for-desktop` in Ubuntu - I simply want to SMS from my desktop with this.

Or ideally, have more options on *which* desktop notifications show up, and then I can choose SMS only.

Thanks!

## 🏡 Environmental Context
**Operating System**
Ubuntu

**Comment by sidneys** [comment]
@clutchwave 

Thanks for your suggestion - a rather unusual user scenario, however trivial. The feature will ship in the next release.

**Comment by sidneys** [comment]
@clutchwave 

This has just been [shipped](https://github.com/sidneys/pb-for-desktop/releases).
Looking forward to your feedback.
