### ISSUE TITLE
Disable/filter certain notifications

### ISSUE THREAD

**Issue by YodaEmbedding** [sidneys/pb-for-desktop#76]
It would be nice to selectively disable certain types of notifications.

**Use case:** For instance, disabling Facebook Messenger notifications.

**Comment by sidneys** [comment]
@SicariusNoctis 

Thank you for your suggestion – could you elaborate? How would you expect this feature work from a User Story perspective (e.g. simple text-based filters, a more involved graphical interface,...)?

Cheers. S

**Comment by sidneys** [comment]
@SicariusNoctis 

This has just been shipped with release [v6.8.1](https://github.com/sidneys/pb-for-desktop/releases). Looking forward to your feedback.

**Comment by sidneys** [comment]
Closing due to missing information.

**Comment by YodaEmbedding** [comment]
Sorry for the late response.

For a typical user, the simplest method would be a mute button on a notification, just like the official Pushbullet app:

![](https://i.imgur.com/15bUgz6.png)

Personally, I use a [very minimal notification daemon](https://github.com/dunst-project/dunst), without buttons, and would enjoy configuring a text file instead. For instance, one could filter by app name:

    [Mute]
    Messenger
    WhatsApp

Or perhaps more advanced filters for content:

    {
        "app": "Messenger",
        "content": "^John Smith.*",
        "filter": "mute"
    }

In this example, I dislike reading messages from John Smith on my work PC.

**Comment by sidneys** [comment]
@SicariusNoctis 

Thanks for the continuing feedback.

A beta version of this feature will ship shortly, using a plaintext file where filtering terms (regular expressions) can be inserted, against which each notifications `body` and `title` will be tested, similar as per your proposal.

Cheers, S

**Comment by sidneys** [comment]
@SicariusNoctis 

This feature is included as of version [v9.0.0](https://github.com/sidneys/pb-for-desktop/releases/tag/v9.0.0). If any issues should occur, your feedback is very much welcome.

Cheers, S
