### ISSUE TITLE
Copying text and navigating problems

### ISSUE THREAD

**Issue by jaredbidlow** [sidneys/pb-for-desktop#77]
## 🤷🏽‍♂️ Current Behaviour

Press tab in the program, navigate through all of the ui elements and the top-level links, enter chat area and tab through the links in the chat history.

## 🎯 Expected Behaviour

I have a suggestion: allow quick entry into the chat history with a keyboard shortcut. Allow focusing (using the tab key) on all messages, and not just links. When focused, allow the user to copy the text of the message without highlighting the text through mouse movement. Currently using a touch screen laptop where copying text is unavailable to me through this app

-->
**App Version**
v0.0.1
**Installation Type** 
Setup
**Operating System**
Windows 10 Enterprise x64 (15042.00)

**Comment by sidneys** [comment]
@jaredbidlow 
Great idea - thanks for the suggestion.

Albeit at first unintuitive, this feature greatly enhances the apps' versatility while at the same time increasing its accessibility, and can be achieved by merely relying upon established web standards (progressively injecting features into the default Pushbullet web app). Slated for next release.

**Comment by sidneys** [comment]
@jaredbidlow 

These features have been added to [v6.9.0](https://github.com/sidneys/pb-for-desktop/releases).
Please test and submit your feedback.

Cheers,
S

**Comment by crash83k** [comment]
I'll give a try today. Thanks!
