### ISSUE TITLE
Action button dismisses notification, but doesn't launch anything

### ISSUE THREAD

**Issue by rmountjoy92** [sidneys/pb-for-desktop#80]
## 🤷🏽‍♂️ Current Behaviour

Notification action button doesn't do anything except dismiss the notification.

## 🎯 Expected Behaviour

Action button should open respective source.

## 👟 Steps to Reproduce (S2R)

 1. get notification
 2. click 'view'

## 🏡 Environmental Context

**App Version**
v6.8.1
**Installation Type** 

AppImage and .deb (tried both)

**Operating System**
OS: Ubuntu 16.04 xenial
 Kernel: x86_64 Linux 4.8.17-galliumos
 DE: XFCE
 WM: Xfwm4

**Comment by sidneys** [comment]
@rmountjoy92 

Thanks for your feedback!

However, notification actions or click events are not supported by XFCE (see https://docs.xfce.org/apps/notifyd/spec), thus there is no possibility of getting this feature to run. 

Apart from, of course, switching to Ubuntu 17.10 / Gnome, where interactive notifications are supported 😇

Cheers, closing for now
S
