### ISSUE TITLE
I'm getting the same notifications, I've dismissed previously, every time I start the app

### ISSUE THREAD

**Issue by shoguevara** [sidneys/pb-for-desktop#83]
Yet it's affecting my own pushes to other devices notifications and IFTT notifications.
Dismissing the notification only helps till next app launch. If I want to permanently silence them - I hove to delete them
**App Version**
v7.0.0 (had the same issue with 6.8.1)
**Installation Type** 
DMG Image
**Operating System**
Mac OS X 10.13.4

**Comment by whispy** [comment]
I am having the same issue.

**App Version**
Both v7.0.0 and v7.2.0

**OS**
macOS 10.12.6

Please let me know if I can provide more information.

**Comment by sidneys** [comment]
@shoguevara 
@whispy 

Thanks for your feedback.
How are you dismissing the pushes?
What kind of pushes are affected?

Kind regards.

**Comment by whispy** [comment]
I am not dismissing the pushes in any way — I don't see a dismiss button anywhere. The pushes show as normal system notifications.

I have only tested it with text pushes from other devices using Pushbullet.

It seems like this issue _may_ have been fixed with v7.4.0, but I will test out a bit more.

**Comment by shoguevara** [comment]
I'm dismissing them wiping away or pressing the cross in the top right corner of the notification center 
I get repeating notifications from my own pushes from other devices, IFTT and now the update notification
Here's an example for you - I haven't dismissed previous update notification and after relaunching I got 2 of them - https://pasteboard.co/HpB4ulf.png

**Comment by whispy** [comment]
I don't get this behavior in v7.6.0. It seems to be fixed 👍

**Comment by whispy** [comment]
Disregard my previous comment — it's not fixed.

**Comment by shoguevara** [comment]
I can't confirm that Im experiencing the same issue in Version 7.6.0. It seems to be fixed.

**Comment by shoguevara** [comment]
@whispy can you confirm that the bug is still there?

**Comment by whispy** [comment]
I am still seeing it on 7.6.0 when I quit and reopen the app.

**Comment by shoguevara** [comment]
> I am still seeing it on 7.6.0 when I quit and reopen the app.

Have you tried unticking "Replay pushes on launch" from the tray menu? Or isn't the issue relevant anymore?

**Comment by shoguevara** [comment]
@sidneys it seems this issue can be closed

**Comment by Piohm** [comment]
Hello! I got this issue with a picture uploaded to PB for Desktop if I remember correctly.
Here is how I "fixed" it (v.8.18.2):
I deleted the picture in PB for Desktop, shut down the app, cleared all the notifications from Notification Center, restarted the app twice (first one didn't fix the issue → shut down, clear again), and the buggy notification was gone.
