### ISSUE TITLE
A JavaScript error occurred in the  main process

### ISSUE THREAD

**Issue by royhenengel** [sidneys/pb-for-desktop#86]
## 🤷🏽‍♂️ Current Behaviour
Got a notification about version 7.4.0. 
Tried to update but there was an error, so I tried to directly download the updated version.
After installing the new version, got this error:

![2018-06-13_21-29-00](https://user-images.githubusercontent.com/13081692/41371475-1b53ff76-6f53-11e8-8c12-5b3de978bc4f.png)

## 🎯 Expected Behaviour
Should open the app

## 👟 Steps to Reproduce (S2R)
 1. Download version 7.4.0
 2. Copy to Applications folder
 3. Right click the app, and open it

## 🏡 Environmental Context
**App Version**
v7.4.0
**Installation Type** 
Setup
**Operating System**
macOS 10.13.5

**Comment by riemannulus** [comment]
Oh, same issue, just I opened... I'll closed my issue https://github.com/sidneys/pb-for-desktop/issues/87

**Comment by sidneys** [comment]
Hi @henengel 

This has been fixed as of [v7.6.0](https://github.com/sidneys/pb-for-desktop/releases).

Cheers,
S
