### ISSUE TITLE
Error: Cannot find module '/tmp/.mount_pb-for4XKagy/resources/electron.asar/browser/init.js'

### ISSUE THREAD

**Issue by rolfep** [sidneys/pb-for-desktop#88]
## 🤷🏽‍♂️ Current Behaviour

I just downloaded pb-for-desktop-7.6.0-x86_64.AppImage (thanks!) in the Seamonkey browser to /tmp on Mageia release 6 (Official) for x86_64, made the file executable per google (my first appimage), and ran it from konsole.  A program icon was placed in my plasma5 menu under Tools but it fails to launch.
When I run from konsole, the message in Title is included in the output, copied below:
...
[rolf@z68x ~]$ cd /tmp/mozilla_rolf0/
[rolf@z68x mozilla_rolf0]$ ll
total 86632
-rwx--x--x 1 rolf rolf 88708003 Jun 17 08:10 pb-for-desktop-7.6.0-x86_64.AppImage*
[rolf@z68x mozilla_rolf0]$ ./pb-for-desktop-7.6.0-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_pb-for4XKagy/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
[rolf@z68x mozilla_rolf0]$ ps aux | grep bullet
rolf      5638  0.0  0.0  26128   872 pts/0    S+   08:23   0:00 grep --color bullet
[rolf@z68x mozilla_rolf0]$
...
## 🎯 Expected Behaviour

A program to launch in the gui, with certain configurations and capabilities explained.

## 👟 Steps to Reproduce (S2R)

I think was answered above.

## 🏡 Environmental Context

**App Version**
v7.6.0
**Installation Type** 
appimage
**Operating System**
Mageia release 6 (Official) for x86_64

**Comment by sidneys** [comment]
@rolfep 

Thanks for your feedback. This is an upstream issue:
https://github.com/electron-userland/electron-builder/issues/2958

Until it is fixed, please fallback to one of the other package formats.

Cheers,
S
