### ISSUE TITLE
Bad URI for Debian package download

### ISSUE THREAD

**Issue by guiNovais** [sidneys/pb-for-desktop#89]
The download icon for Debian available at https://sidneys.github.io/pb-for-desktop/#download sends to a GitHub 404 page.

I've notice that he try to download at the following uri:https://github.com/sidneys/pb-for-desktop/releases/download/v7.6.0/pb-for-desktop_7.6.0_amd64.deb

Although, I've found the actual link is: https://github.com/sidneys/pb-for-desktop/releases/download/v7.6.0/pb-for-desktop-7.6.0-amd64.deb

**Comment by sidneys** [comment]
@guiAlberto 

Thanks for the heads-up. The URL has been fixed.

Cheers,
S
