### ISSUE TITLE
High CPU and memory usage (possible leak)

### ISSUE THREAD

**Issue by z0rc** [sidneys/pb-for-desktop#90]
## 🤷🏽‍♂️ Current Behaviour

The PB-for-Desktop process children, seems like Electron component takes too much CPU and memory. It increases usage over time, as on start it was minimal, but risen on course of 6 hours.

![image](https://user-images.githubusercontent.com/787519/42728843-597ca7e8-87cd-11e8-9633-80b75a4be793.png)
Here 82.5 is CPU usage percentage and 54.5 is memory usage percentage.

## 🎯 Expected Behaviour

Minimal resource usage.

## 👟 Steps to Reproduce (S2R)

Not sure about this, I'm seeing this every time I run PB-for-Desktop for prolonged period of time.

## 🏡 Environmental Context

**App Version**
v7.6.0
**Installation Type** 
Deb package
**Operating System**
Kubuntu 18.04

**Comment by fancypantalons** [comment]
I'm seeing the same thing here.  Stock Ubuntu 18.04, v7.6.0.  Eventually PB started flat out pegging the CPU, and I've been forced to just run it on demand as I need it.

Let me know if there's anything I can do to trace or debug the issue.

**Comment by cbanack** [comment]
I'm seeing the same problem...regular Ubuntuo 18.04, PB v7.6.   As soon as I boot up and start PB, `top` shows that it's taking around 25% of a cpu, and that usage amount never drops.

**Comment by z0rc** [comment]
Sorry, but I cannot help with this ticket. I stopped using PB for good.
