### ISSUE TITLE
Fails on all current distros

### ISSUE THREAD

**Issue by alongfield** [sidneys/pb-for-desktop#97]
## 🤷🏽‍♂️ Current Behaviour

All current releases based on Fedora or Ubuntu fail to run this app.  This happens on Ubuntu derivatives with the deb packages, and Fedora distros from rpm.  The appimage does not work and fails with the same issue.

A JavaScript error occurred in the main process
Uncaught Exception:
RangeError: Maximum call stack size exceeded
    at write (console.js:165:9)
    at Console.log (console.js:197:3)
    at crawl (/tmp/.mount_pb-for2VxpQ0/resources/app.asar/node_modules/package.loader/lib/tools/crawler.js:47:13)

## 🎯 Expected Behaviour

The application should start and be usable.

## 👟 Steps to Reproduce (S2R)

 1. Install on distro based on F29 or Ubuntu 18.04+,
 2. Try to start pb-for-desktop

## 🏡 Environmental Context

**App Version**
vALL
**Installation Type** 
RPM, DEB, AppImage
**Operating System**
F29, Ubuntu 18.04, Ubuntu 18.10

**Comment by Halvhjearne** [comment]
pb-for-desktop seems to work on ubuntu 18.10.
it can start up and send messages, alltho it seems like it does not know if the message was actually send or not and if i try to send messages to pb-for-desktop, it seems like no new messages will be received after startup.
if the program is restarted or i use the reconnect feature, all missing messages will then show up.

an error message sometimes appears with the option to send an error report, however the window closes if i try to fill out the form.

**Comment by madmangr** [comment]
Same issue with Arch Linux.  This seems to be an issue with several versions I've tried in Arch.  If I click Blog and then the PB logo the error message disappears and the application begins working again.  I also have Ubuntu 18.10 installed and the exact same issue.

**Comment by fernandex00** [comment]
On Ubuntu 18.10 not getting any notifications and don't sincronized, but i can send pushes to other devices

**Comment by pjbuterbaugh** [comment]
While the app is usable and autostarts, SMS mirror or push notifications do not work.

Running Xubuntu 18.10.

**Comment by sidneys** [comment]
@alongfield @pjb0521 Please validate whether this issue still occurs in the new version (10.0.1). Thanks.

**Comment by pjbuterbaugh** [comment]
@sidneys Notifications seem to be functional. Thank you for the fix!

**Comment by Halvhjearne** [comment]
i still get an error, but a diffrent message now:
![Skærmbillede fra 2019-11-15 22-55-53](https://user-images.githubusercontent.com/6340219/68978579-6facc200-07fb-11ea-8ab6-1d43fa873815.png)

 but it seems to work anyway

**Comment by sidneys** [comment]
> @sidneys Notifications seem to be functional. Thank you for the fix!

@pjb0521

You are most welcome.

**Comment by sidneys** [comment]
> i still get an error, but a diffrent message now:
> but it seems to work anyway

Thank you for the report. A fix for this issue has just been deployed in [version 10.2.0](https://github.com/sidneys/pb-for-desktop/releases/tag/v10.2.0). Please and add your feedback should it reoccur, the issue will then be reopened.

Kind regards, S

**Comment by Halvhjearne** [comment]
seems like its fixed now, thanks a lot :)

**Comment by alongfield** [comment]
Rebuilt from installed 9.5.0 in Arch AUR with a manual change to get 10.2.0 in the build file.  Built and installed fine and seems to be all set.  Thanks!
