### ISSUE TITLE
Inconsistent 'back' behavior

### ISSUE THREAD

**Issue by HankAviator** [sidneys/pb-for-desktop#98]
## 🤷🏽‍♂️ Current Behaviour

Clicking 'back' button on sms page brings page back to first option (_people_), instead of the previously opened one (_sms_).

## 🎯 Expected Behaviour

Go back to where I'm from.

## 👟 Steps to Reproduce (S2R)

Quite self-explantory.

## 🏡 Environmental Context

**App Version**
v8.1.1
**Installation Type** 
Setup
**Operating System**
Windows 10 Pro x64 (10.0.17763) (Irrelavant)

**Comment by sidneys** [comment]
@HankAviator 

This is the standard behavior as deployed via the default Pushbullet web application. Apart from stylistic & performance-related tweaks, overhauling its user flow is not within the scope of this project.

Cheers, S
