### ISSUE TITLE
Uncaught exception: Max call stack exceed

### ISSUE THREAD

**Issue by HankAviator** [sidneys/pb-for-desktop#99]
## 🤷🏽‍♂️ Current Behaviour

App opens when system boots up with an error message.

## 🎯 Expected Behaviour

No error.
## 👟 Steps to Reproduce (S2R)

1. boot the system, wait for app to open
2. error message
![image](https://user-images.githubusercontent.com/8069557/50381012-85cb0480-06b6-11e9-9e98-b49b431c5ac6.png)

## 🏡 Environmental Context

**App Version**
v8.1.1
**Installation Type** 
Setup
**Operating System**
Windows 10 Pro x64 (17763.00)

**Comment by sidneys** [comment]
@HankAviator  

Thank you for your feedback. Was this issue resolved with one of the [recent releases](https://github.com/sidneys/pb-for-desktop/releases)?

Cheers,
S

**Comment by HankAviator** [comment]
Hi Sidneys,

Unfortunately I already switched to official Pushbullet since I didn't get timely response on this issue.

**Comment by sidneys** [comment]
@HankAviator 

Okay - thanks anyways for your input nonetheless.
If you are to give PB4D another go in the future, you are more than welcome.

Cheers, S
